// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for SsoCallbackParamsProvider.
const (
	SsoCallbackParamsProviderGoogle    SsoCallbackParamsProvider = "google"
	SsoCallbackParamsProviderMicrosoft SsoCallbackParamsProvider = "microsoft"
)

// Defines values for StartSsoLoginParamsProvider.
const (
	StartSsoLoginParamsProviderGoogle    StartSsoLoginParamsProvider = "google"
	StartSsoLoginParamsProviderMicrosoft StartSsoLoginParamsProvider = "microsoft"
)

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// CreateOrganizationRequest defines model for CreateOrganizationRequest.
type CreateOrganizationRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Error Standard error envelope for every non-2xx response. Chosen over bare
// RFC 7807 so the correlation `request_id` is a first-class field the SPA
// and CLI can surface directly; `code` is stable for programmatic handling.
type Error struct {
	Error struct {
		// Code Stable, machine-readable error code.
		Code string `json:"code"`

		// Details Field-level problems (e.g. validation failures).
		Details *[]ErrorDetail `json:"details,omitempty"`

		// Message Human-readable explanation.
		Message string `json:"message"`

		// RequestId Correlation ID; match against server logs.
		RequestId *string `json:"request_id,omitempty"`
	} `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Field Dotted path to the offending field, when applicable.
	Field *string `json:"field,omitempty"`

	// Message What is wrong with this field.
	Message string `json:"message"`
}

// GenericMessage defines model for GenericMessage.
type GenericMessage struct {
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// RequestId Correlation ID for this request.
	RequestId *string `json:"request_id,omitempty"`

	// Service Reporting service name.
	Service string `json:"service"`

	// Status Liveness status.
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus Liveness status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     *string             `json:"name,omitempty"`
	Password string              `json:"password"`
}

// SsoConfigRequest defines model for SsoConfigRequest.
type SsoConfigRequest struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Enabled      bool   `json:"enabled"`

	// TenantId Required for Microsoft (the org's Entra tenant ID); unused by Google.
	TenantId *string `json:"tenant_id,omitempty"`
}

// SsoRedirect defines model for SsoRedirect.
type SsoRedirect struct {
	RedirectUrl string `json:"redirect_url"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// UpdateOrganizationRequest Only the name is mutable; the slug is fixed at creation.
type UpdateOrganizationRequest struct {
	Name string `json:"name"`
}

// SsoCallbackParams defines parameters for SsoCallback.
type SsoCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// SsoCallbackParamsProvider defines parameters for SsoCallback.
type SsoCallbackParamsProvider string

// StartSsoLoginParams defines parameters for StartSsoLogin.
type StartSsoLoginParams struct {
	// Org Organization slug whose SSO config to use.
	Org string `form:"org" json:"org"`
}

// StartSsoLoginParamsProvider defines parameters for StartSsoLogin.
type StartSsoLoginParamsProvider string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirmRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = TokenRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationRequest

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = UpdateOrganizationRequest

// SetSsoConfigJSONRequestBody defines body for SetSsoConfig for application/json ContentType.
type SetSsoConfigJSONRequestBody = SsoConfigRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Verify credentials
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the current session
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Request a password-reset email
	// (POST /api/v1/auth/password-reset)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)
	// Set a new password using a reset token
	// (POST /api/v1/auth/password-reset/confirm)
	ConfirmPasswordReset(w http.ResponseWriter, r *http.Request)
	// Create a local account (sends a verification email)
	// (POST /api/v1/auth/signup)
	Signup(w http.ResponseWriter, r *http.Request)
	// SSO callback (enterprise)
	// (GET /api/v1/auth/sso/{provider}/callback)
	SsoCallback(w http.ResponseWriter, r *http.Request, provider SsoCallbackParamsProvider, params SsoCallbackParams)
	// Begin an SSO login (enterprise)
	// (GET /api/v1/auth/sso/{provider}/start)
	StartSsoLogin(w http.ResponseWriter, r *http.Request, provider StartSsoLoginParamsProvider, params StartSsoLoginParams)
	// Verify an email address with a token
	// (POST /api/v1/auth/verify-email)
	VerifyEmail(w http.ResponseWriter, r *http.Request)
	// List organizations
	// (GET /api/v1/organizations)
	ListOrganizations(w http.ResponseWriter, r *http.Request)
	// Create an organization
	// (POST /api/v1/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request)
	// Soft-delete an organization
	// (DELETE /api/v1/organizations/{orgId})
	DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID)
	// Get an organization
	// (GET /api/v1/organizations/{orgId})
	GetOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID)
	// Update organization settings (name only; slug is immutable)
	// (PATCH /api/v1/organizations/{orgId})
	UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID)
	// Configure an SSO provider for an organization (enterprise)
	// (PUT /api/v1/organizations/{orgId}/sso/{provider})
	SetSsoConfig(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID, provider string)
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Verify credentials
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke the current session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a password-reset email
// (POST /api/v1/auth/password-reset)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set a new password using a reset token
// (POST /api/v1/auth/password-reset/confirm)
func (_ Unimplemented) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a local account (sends a verification email)
// (POST /api/v1/auth/signup)
func (_ Unimplemented) Signup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSO callback (enterprise)
// (GET /api/v1/auth/sso/{provider}/callback)
func (_ Unimplemented) SsoCallback(w http.ResponseWriter, r *http.Request, provider SsoCallbackParamsProvider, params SsoCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin an SSO login (enterprise)
// (GET /api/v1/auth/sso/{provider}/start)
func (_ Unimplemented) StartSsoLogin(w http.ResponseWriter, r *http.Request, provider StartSsoLoginParamsProvider, params StartSsoLoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify an email address with a token
// (POST /api/v1/auth/verify-email)
func (_ Unimplemented) VerifyEmail(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List organizations
// (GET /api/v1/organizations)
func (_ Unimplemented) ListOrganizations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organization
// (POST /api/v1/organizations)
func (_ Unimplemented) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete an organization
// (DELETE /api/v1/organizations/{orgId})
func (_ Unimplemented) DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an organization
// (GET /api/v1/organizations/{orgId})
func (_ Unimplemented) GetOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update organization settings (name only; slug is immutable)
// (PATCH /api/v1/organizations/{orgId})
func (_ Unimplemented) UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Configure an SSO provider for an organization (enterprise)
// (PUT /api/v1/organizations/{orgId}/sso/{provider})
func (_ Unimplemented) SetSsoConfig(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID, provider string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SsoCallback operation middleware
func (siw *ServerInterfaceWrapper) SsoCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider SsoCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", chi.URLParam(r, "provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SsoCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SsoCallback(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartSsoLogin operation middleware
func (siw *ServerInterfaceWrapper) StartSsoLogin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider StartSsoLoginParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", chi.URLParam(r, "provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StartSsoLoginParams

	// ------------- Required query parameter "org" -------------

	if paramValue := r.URL.Query().Get("org"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "org"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "org", r.URL.Query(), &params.Org)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartSsoLogin(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrganization operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrganization operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetSsoConfig operation middleware
func (siw *ServerInterfaceWrapper) SetSsoConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", chi.URLParam(r, "provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetSsoConfig(w, r, orgId, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password-reset", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/signup", wrapper.Signup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/sso/{provider}/callback", wrapper.SsoCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/sso/{provider}/start", wrapper.StartSsoLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/verify-email", wrapper.VerifyEmail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations", wrapper.ListOrganizations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/organizations", wrapper.CreateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/organizations/{orgId}", wrapper.DeleteOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations/{orgId}", wrapper.GetOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/organizations/{orgId}", wrapper.UpdateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/organizations/{orgId}/sso/{provider}", wrapper.SetSsoConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})

	return r
}

type ErrorResponseHeaders struct {
	XRequestId string
}
type ErrorJSONResponse struct {
	Body Error

	Headers ErrorResponseHeaders
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	XRequestId string
}

type Login200JSONResponse struct {
	Body    AuthUser
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type LogindefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response LogindefaultJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	XRequestId string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(204)
	return nil
}

type LogoutdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response LogoutdefaultJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RequestPasswordResetRequestObject struct {
	Body *RequestPasswordResetJSONRequestBody
}

type RequestPasswordResetResponseObject interface {
	VisitRequestPasswordResetResponse(w http.ResponseWriter) error
}

type RequestPasswordReset202ResponseHeaders struct {
	XRequestId string
}

type RequestPasswordReset202JSONResponse struct {
	Body    GenericMessage
	Headers RequestPasswordReset202ResponseHeaders
}

func (response RequestPasswordReset202JSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response.Body)
}

type RequestPasswordResetdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response RequestPasswordResetdefaultJSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ConfirmPasswordResetRequestObject struct {
	Body *ConfirmPasswordResetJSONRequestBody
}

type ConfirmPasswordResetResponseObject interface {
	VisitConfirmPasswordResetResponse(w http.ResponseWriter) error
}

type ConfirmPasswordReset200ResponseHeaders struct {
	XRequestId string
}

type ConfirmPasswordReset200JSONResponse struct {
	Body    GenericMessage
	Headers ConfirmPasswordReset200ResponseHeaders
}

func (response ConfirmPasswordReset200JSONResponse) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ConfirmPasswordResetdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response ConfirmPasswordResetdefaultJSONResponse) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup202ResponseHeaders struct {
	XRequestId string
}

type Signup202JSONResponse struct {
	Body    GenericMessage
	Headers Signup202ResponseHeaders
}

func (response Signup202JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response.Body)
}

type SignupdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response SignupdefaultJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SsoCallbackRequestObject struct {
	Provider SsoCallbackParamsProvider `json:"provider"`
	Params   SsoCallbackParams
}

type SsoCallbackResponseObject interface {
	VisitSsoCallbackResponse(w http.ResponseWriter) error
}

type SsoCallback302ResponseHeaders struct {
	Location string
}

type SsoCallback302Response struct {
	Headers SsoCallback302ResponseHeaders
}

func (response SsoCallback302Response) VisitSsoCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type SsoCallbackdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response SsoCallbackdefaultJSONResponse) VisitSsoCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type StartSsoLoginRequestObject struct {
	Provider StartSsoLoginParamsProvider `json:"provider"`
	Params   StartSsoLoginParams
}

type StartSsoLoginResponseObject interface {
	VisitStartSsoLoginResponse(w http.ResponseWriter) error
}

type StartSsoLogin200ResponseHeaders struct {
	XRequestId string
}

type StartSsoLogin200JSONResponse struct {
	Body    SsoRedirect
	Headers StartSsoLogin200ResponseHeaders
}

func (response StartSsoLogin200JSONResponse) VisitStartSsoLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type StartSsoLogindefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response StartSsoLogindefaultJSONResponse) VisitStartSsoLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VerifyEmailRequestObject struct {
	Body *VerifyEmailJSONRequestBody
}

type VerifyEmailResponseObject interface {
	VisitVerifyEmailResponse(w http.ResponseWriter) error
}

type VerifyEmail200ResponseHeaders struct {
	XRequestId string
}

type VerifyEmail200JSONResponse struct {
	Body    GenericMessage
	Headers VerifyEmail200ResponseHeaders
}

func (response VerifyEmail200JSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type VerifyEmaildefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response VerifyEmaildefaultJSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListOrganizationsRequestObject struct {
}

type ListOrganizationsResponseObject interface {
	VisitListOrganizationsResponse(w http.ResponseWriter) error
}

type ListOrganizations200ResponseHeaders struct {
	XRequestId string
}

type ListOrganizations200JSONResponse struct {
	Body    []Organization
	Headers ListOrganizations200ResponseHeaders
}

func (response ListOrganizations200JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListOrganizationsdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response ListOrganizationsdefaultJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateOrganizationRequestObject struct {
	Body *CreateOrganizationJSONRequestBody
}

type CreateOrganizationResponseObject interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization201ResponseHeaders struct {
	XRequestId string
}

type CreateOrganization201JSONResponse struct {
	Body    Organization
	Headers CreateOrganization201ResponseHeaders
}

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response CreateOrganizationdefaultJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteOrganizationRequestObject struct {
	OrgId openapi_types.UUID `json:"orgId"`
}

type DeleteOrganizationResponseObject interface {
	VisitDeleteOrganizationResponse(w http.ResponseWriter) error
}

type DeleteOrganization204ResponseHeaders struct {
	XRequestId string
}

type DeleteOrganization204Response struct {
	Headers DeleteOrganization204ResponseHeaders
}

func (response DeleteOrganization204Response) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(204)
	return nil
}

type DeleteOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response DeleteOrganizationdefaultJSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOrganizationRequestObject struct {
	OrgId openapi_types.UUID `json:"orgId"`
}

type GetOrganizationResponseObject interface {
	VisitGetOrganizationResponse(w http.ResponseWriter) error
}

type GetOrganization200ResponseHeaders struct {
	XRequestId string
}

type GetOrganization200JSONResponse struct {
	Body    Organization
	Headers GetOrganization200ResponseHeaders
}

func (response GetOrganization200JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response GetOrganizationdefaultJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateOrganizationRequestObject struct {
	OrgId openapi_types.UUID `json:"orgId"`
	Body  *UpdateOrganizationJSONRequestBody
}

type UpdateOrganizationResponseObject interface {
	VisitUpdateOrganizationResponse(w http.ResponseWriter) error
}

type UpdateOrganization200ResponseHeaders struct {
	XRequestId string
}

type UpdateOrganization200JSONResponse struct {
	Body    Organization
	Headers UpdateOrganization200ResponseHeaders
}

func (response UpdateOrganization200JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response UpdateOrganizationdefaultJSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SetSsoConfigRequestObject struct {
	OrgId    openapi_types.UUID `json:"orgId"`
	Provider string             `json:"provider"`
	Body     *SetSsoConfigJSONRequestBody
}

type SetSsoConfigResponseObject interface {
	VisitSetSsoConfigResponse(w http.ResponseWriter) error
}

type SetSsoConfig204ResponseHeaders struct {
	XRequestId string
}

type SetSsoConfig204Response struct {
	Headers SetSsoConfig204ResponseHeaders
}

func (response SetSsoConfig204Response) VisitSetSsoConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(204)
	return nil
}

type SetSsoConfigdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response SetSsoConfigdefaultJSONResponse) VisitSetSsoConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200ResponseHeaders struct {
	XRequestId string
}

type GetHealth200JSONResponse struct {
	Body    HealthResponse
	Headers GetHealth200ResponseHeaders
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response GetHealthdefaultJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Verify credentials
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current session
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Request a password-reset email
	// (POST /api/v1/auth/password-reset)
	RequestPasswordReset(ctx context.Context, request RequestPasswordResetRequestObject) (RequestPasswordResetResponseObject, error)
	// Set a new password using a reset token
	// (POST /api/v1/auth/password-reset/confirm)
	ConfirmPasswordReset(ctx context.Context, request ConfirmPasswordResetRequestObject) (ConfirmPasswordResetResponseObject, error)
	// Create a local account (sends a verification email)
	// (POST /api/v1/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)
	// SSO callback (enterprise)
	// (GET /api/v1/auth/sso/{provider}/callback)
	SsoCallback(ctx context.Context, request SsoCallbackRequestObject) (SsoCallbackResponseObject, error)
	// Begin an SSO login (enterprise)
	// (GET /api/v1/auth/sso/{provider}/start)
	StartSsoLogin(ctx context.Context, request StartSsoLoginRequestObject) (StartSsoLoginResponseObject, error)
	// Verify an email address with a token
	// (POST /api/v1/auth/verify-email)
	VerifyEmail(ctx context.Context, request VerifyEmailRequestObject) (VerifyEmailResponseObject, error)
	// List organizations
	// (GET /api/v1/organizations)
	ListOrganizations(ctx context.Context, request ListOrganizationsRequestObject) (ListOrganizationsResponseObject, error)
	// Create an organization
	// (POST /api/v1/organizations)
	CreateOrganization(ctx context.Context, request CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error)
	// Soft-delete an organization
	// (DELETE /api/v1/organizations/{orgId})
	DeleteOrganization(ctx context.Context, request DeleteOrganizationRequestObject) (DeleteOrganizationResponseObject, error)
	// Get an organization
	// (GET /api/v1/organizations/{orgId})
	GetOrganization(ctx context.Context, request GetOrganizationRequestObject) (GetOrganizationResponseObject, error)
	// Update organization settings (name only; slug is immutable)
	// (PATCH /api/v1/organizations/{orgId})
	UpdateOrganization(ctx context.Context, request UpdateOrganizationRequestObject) (UpdateOrganizationResponseObject, error)
	// Configure an SSO provider for an organization (enterprise)
	// (PUT /api/v1/organizations/{orgId}/sso/{provider})
	SetSsoConfig(ctx context.Context, request SetSsoConfigRequestObject) (SetSsoConfigResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestPasswordReset operation middleware
func (sh *strictHandler) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	var request RequestPasswordResetRequestObject

	var body RequestPasswordResetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestPasswordReset(ctx, request.(RequestPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestPasswordReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestPasswordResetResponseObject); ok {
		if err := validResponse.VisitRequestPasswordResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmPasswordReset operation middleware
func (sh *strictHandler) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	var request ConfirmPasswordResetRequestObject

	var body ConfirmPasswordResetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmPasswordReset(ctx, request.(ConfirmPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmPasswordReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConfirmPasswordResetResponseObject); ok {
		if err := validResponse.VisitConfirmPasswordResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Signup operation middleware
func (sh *strictHandler) Signup(w http.ResponseWriter, r *http.Request) {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx, request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SsoCallback operation middleware
func (sh *strictHandler) SsoCallback(w http.ResponseWriter, r *http.Request, provider SsoCallbackParamsProvider, params SsoCallbackParams) {
	var request SsoCallbackRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SsoCallback(ctx, request.(SsoCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SsoCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SsoCallbackResponseObject); ok {
		if err := validResponse.VisitSsoCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartSsoLogin operation middleware
func (sh *strictHandler) StartSsoLogin(w http.ResponseWriter, r *http.Request, provider StartSsoLoginParamsProvider, params StartSsoLoginParams) {
	var request StartSsoLoginRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartSsoLogin(ctx, request.(StartSsoLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartSsoLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartSsoLoginResponseObject); ok {
		if err := validResponse.VisitStartSsoLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyEmail operation middleware
func (sh *strictHandler) VerifyEmail(w http.ResponseWriter, r *http.Request) {
	var request VerifyEmailRequestObject

	var body VerifyEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyEmail(ctx, request.(VerifyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyEmailResponseObject); ok {
		if err := validResponse.VisitVerifyEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrganizations operation middleware
func (sh *strictHandler) ListOrganizations(w http.ResponseWriter, r *http.Request) {
	var request ListOrganizationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizations(ctx, request.(ListOrganizationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationsResponseObject); ok {
		if err := validResponse.VisitListOrganizationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganization operation middleware
func (sh *strictHandler) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	var request CreateOrganizationRequestObject

	var body CreateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganization(ctx, request.(CreateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrganization operation middleware
func (sh *strictHandler) DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	var request DeleteOrganizationRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrganization(ctx, request.(DeleteOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrganizationResponseObject); ok {
		if err := validResponse.VisitDeleteOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrganization operation middleware
func (sh *strictHandler) GetOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	var request GetOrganizationRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrganization(ctx, request.(GetOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrganizationResponseObject); ok {
		if err := validResponse.VisitGetOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrganization operation middleware
func (sh *strictHandler) UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	var request UpdateOrganizationRequestObject

	request.OrgId = orgId

	var body UpdateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrganization(ctx, request.(UpdateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateOrganizationResponseObject); ok {
		if err := validResponse.VisitUpdateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetSsoConfig operation middleware
func (sh *strictHandler) SetSsoConfig(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID, provider string) {
	var request SetSsoConfigRequestObject

	request.OrgId = orgId
	request.Provider = provider

	var body SetSsoConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetSsoConfig(ctx, request.(SetSsoConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetSsoConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetSsoConfigResponseObject); ok {
		if err := validResponse.VisitSetSsoConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xa73LjthF/lR02M7Vb/fH52qa1P118ycXTS+/GuqSdObs2RKxIxCDAAKBsxeOZPkSf",
	"sE/SWYCUSIqyJJ/t6JNlCcBid3+7+O0Cd1Gss1wrVM5GR3dRioyj8R/P8JcCrTvl9A9HGxuRO6FVdBSd",
	"aGNQMvoPTt/CRBtwqbBgwpRjYNJqYHmOzFgQCiyaKRqQOrGDqBfROGGQR0fOFNiLbJxixkiOm+UYHUXW",
	"GaGS6P7+ngbbXCuLflPfGqMNfYi1cqgcfWR5LkXsdzP82dIG72orfmVwEh1FvxsuFB2GX+0wrOalNBX0",
	"P0AlmbZcM8y/+qVp+sE2XRLK4cOFEe+9mFIyTXtTuPRHi14bxrkg0Ux+NDpH4wSpO2HSYi/Ka1/dRZgx",
	"IenDRJuMueio/KbXtl0v/HA5RSMmAnnNvGOtJTJFYwRvrFUUgi8vdV932efID6mktoRczCfr8c8YO5Jx",
	"YpA5/GASpsSv3k+lWbZUXbEM6W/Gbt+jSlwaHR0eHPSiTKjq/1cdZrCySFrT/vK6PStnzqEh3//7M+v/",
	"etD/28Uf9/rzj/t/+GqtWfz2SnFdZphj90GVm0AcOaY4MxzQIxLVFKXO0YccTtHMQGnVP7y9XYAVTlJt",
	"UYGmiBszg+fq7LsT+PqvB1+D1eBShLgWv1dl0F4KfgXCAoOJMNb1Y8mshYlAyf2c0cc354opDifvTyFm",
	"CmxhJixG4MJg7OTsGK5izdEvYh0by7DL3OjEsCxjTsSQMsWlUMngXEVLwN7IPM05JHA5PY289B5kLE6F",
	"wr5Bxv1+ghFpEoU03rIsl+Qjpd3lRBeKd0URR8eEtMtiviPb9CVOUZKWY4mZhT0cJAOYMil4sO+ECVkY",
	"tPskUjjM7EZZ6a2XSvLLDTFj2Iz+z9BalnSo/X2RMVVT9jaXTPlNDLr0Wvh9XYI/hoy5OAWWMKGsa2fz",
	"h6PCu2ix6+XAaI0PMFgZP6VdtoOJR/Gylm+1c8ghZy4FFyJDTyaouFBJQH4PblJUUJ4wY4mdllzpkX+m",
	"zFE43BitErgRJIfOSb/2etOttlkveocKjYh/WIjewh61DT9+B98jky49K9POljvYHHxL7KLTBQRJEXe4",
	"4AxzbRw5tBwClKab4e8KpfC2z3LRubRjrugI//diigqtT3au8JGAqsjIbPq6ZrEVpi2XXWy9y8bvdSIe",
	"eViu5gm1c/D14UGHxjmz9kYb3nXWPqxUJWK+QpdSdSKwbb73TIJfMtfQjDOHfSf88bukzUYMpzcnFyvp",
	"w9IPRc633EwXj6qzhl5dwYaALjt+LI18hhbdiVYTYbLHYeUhh9dp0mGH3Zy+RrU1K2tZIiyyBjcNfV84",
	"KDpx3rXJkUhUkb94yK6ixlvF9sOufkyoj6z2wEweZ5BYClTVIVHb7Z83YP3lXIuxQfeI+ajovF9RNTlU",
	"THWfXmeljfy59YOIjbZ64mDPswuT/N7Ct8oZBmEJOH27fwyFKixyGM/gndZJYBnbJd6FpdqaLzRZ4aAz",
	"DAx+6xM8TLssjFxPJBqjuzbyiTLA41DyhBmoa2c/+iz8mOq1CYwPSs48x6RYJVaYFb5OOfZfUv4HTw1v",
	"kQNz4E+Ckrs/QRncVat2cnGLcWGEm42oGqmqLH0t8E1BK99FgpQJX1XHV0WhLi1aS9ouqpZc/B1nocUi",
	"1ER3sT3ljJZ9KlYQ3nw89YHzya83EHoAn4j72RxjMo83lVCJRLC6MDExdnCmcOnRuaIf3+mqPKEd2KGv",
	"ONFYoNKVBnya5Tjy8iEECjCDkBCdpsMWJkZnINy52rvK2PXil6v9nl+DGzFxvqoLuxkXQnJoDe7HKcbX",
	"V/uhznXCeZ4ZlCIdo140RWODBQ4GrwYHhDSdoyISehS9HhwMXvvk6lLvgiHLxXD6asgKlw4lsUJ/buuA",
	"wlb5ezh4BWVDxhKOOConmLTHMDocHAL66lzYFEt7BqdB8CnhjdDmwXfKieh6cfOC8RvNZ0/WgWsQ3Psm",
	"Sp0psN3/Ozw4eDLZ8wZcRwPwZGG1UMw/VQ+QBE1YId2qWXN1593JRUxGR58vepEtsoyZWXQU/UROntVd",
	"TGhjiaUQJ6hEFzS9DR5duNXoOeWY5ZqsC//7z38hlr6HG7pGhA8fBAan+roFHzGB3KBF5TohREKXnPmn",
	"jrJKJwly0IXbSZOfec2DPQpjyEy1pPew6Suq1CczNVzQtFa5+wbffab46+TUG8Xh4ZPtodXK6IjGN3GM",
	"uUM+gHIsGLSFdGAwYYZLqsL1BG5SdCll/hTB01PAW2Gd3VEg+ZWBQRMWMG/nbwOmYRzqv9WgKgvEFwdV",
	"qzB94Ry/HlvVZqGstncSLCMkoCi8mYMFCqJBwCCApiqg14DG+up0NUhC9fpMsGiWxjucZM7QFUaVpxuR",
	"9aSZdao8ow0o7Wrp5oZZYNIg4zNKTcI6NDuKqHAnBwykjpkEFse6UA72LCpugZX8MZg6aLe/AbysHt7l",
	"Rk8FR3M/jJmUYxZf034T7IKb1SfVGCK7hmXovJk+l3UGEeBFlVEt/eAVctWETXwpTZV0VYR3NmVLQb8U",
	"aGYLSeWtxeYX1SvWsY657Ra6aAXB6xAELawWLiXGF/uShXhak8SDRdeDsdE3Fg1UxTfy6pqD5XkLle91",
	"PG/IbnE9/8RpbvQBKtDAHiqHJjfCYh161ur1yLOOGbcadvTryOqqsPmtgNfqD9Q6DKEdcJNqi+CN4pto",
	"5L0iPEfowpo2yRch7SnP3XpfqSPXfkoRTvnHOTLhx7P35UUPVmW506DYVCSUppzeyST6DSZCAVPeR74q",
	"3w61PsnO+vO+b/ehHKq8b0ta+Bwnc6P5tnMM7afybckul+CsPCSBcW6oHPGXvWwDXqZrYW9rKat92Whd",
	"ICSN8SGZNw6DgjL+GKVWiS3jplWLC+s+NIR+oXc3etTQuPRbetWw7PTGDn9bz899TZZr2r/m2eb3F/e9",
	"Ff2VQLwsIaY+ZQCnKvg3RwUYusrlawHfayRAnasrbZJLKTLhLg2yOEV+BVrFCFo1oVGWvqG5vMhJoV15",
	"rpiU+sZCVkgncomhT9kqGJdebT1T9ln9PGyjVPTqyTbSxGj3qVVe0DZ9txvwrCh9E1gPQHRVFhreaZOc",
	"8vsAXokOlw+lt/77JXSs6+6FaXxHLDbSE9cPGm5htl43q3yH7mFzHLwoUHcQoO/QbWXm9bzc4/RB0rvu",
	"ZeuFv2SJ02V/Lt/7PVP+W33B+MJUbBNYlV2yXYRXsGPzFLTonCAmtOdvXbWSs+P5XavIyivY/S9Ikq3S",
	"MzyneX7c9l6qTqUAKbqKaHTz1x3P1TBsvx7ZKB46Tp0Rm+7MmRM0KgxWdWPlM1//ttLj+nIy9a8wf11Z",
	"OIT3j5akxFSXyPLV4gD+oQFvHRrFJHDMUXFUsSBmahD8/XWw2dIpFx5+Puf51npauiIVVQ86hQVGau1k",
	"fTh/JZobPca6C2fWYUZebM5uPrf4fEEBGF40hGzSRnaGfW2Ebz34YRzGmIrysQPyBEElQt0SevxLnWgY",
	"3V/c/z8AAP//LFR0I/gzAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
