// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// CreateOrganizationRequest defines model for CreateOrganizationRequest.
type CreateOrganizationRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Error Standard error envelope for every non-2xx response. Chosen over bare
// RFC 7807 so the correlation `request_id` is a first-class field the SPA
// and CLI can surface directly; `code` is stable for programmatic handling.
type Error struct {
	Error struct {
		// Code Stable, machine-readable error code.
		Code string `json:"code"`

		// Details Field-level problems (e.g. validation failures).
		Details *[]ErrorDetail `json:"details,omitempty"`

		// Message Human-readable explanation.
		Message string `json:"message"`

		// RequestId Correlation ID; match against server logs.
		RequestId *string `json:"request_id,omitempty"`
	} `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Field Dotted path to the offending field, when applicable.
	Field *string `json:"field,omitempty"`

	// Message What is wrong with this field.
	Message string `json:"message"`
}

// GenericMessage defines model for GenericMessage.
type GenericMessage struct {
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// RequestId Correlation ID for this request.
	RequestId *string `json:"request_id,omitempty"`

	// Service Reporting service name.
	Service string `json:"service"`

	// Status Liveness status.
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus Liveness status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     *string             `json:"name,omitempty"`
	Password string              `json:"password"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// UpdateOrganizationRequest Only the name is mutable; the slug is fixed at creation.
type UpdateOrganizationRequest struct {
	Name string `json:"name"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirmRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = TokenRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationRequest

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = UpdateOrganizationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Verify credentials
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the current session
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Request a password-reset email
	// (POST /api/v1/auth/password-reset)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)
	// Set a new password using a reset token
	// (POST /api/v1/auth/password-reset/confirm)
	ConfirmPasswordReset(w http.ResponseWriter, r *http.Request)
	// Create a local account (sends a verification email)
	// (POST /api/v1/auth/signup)
	Signup(w http.ResponseWriter, r *http.Request)
	// Verify an email address with a token
	// (POST /api/v1/auth/verify-email)
	VerifyEmail(w http.ResponseWriter, r *http.Request)
	// List organizations
	// (GET /api/v1/organizations)
	ListOrganizations(w http.ResponseWriter, r *http.Request)
	// Create an organization
	// (POST /api/v1/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request)
	// Soft-delete an organization
	// (DELETE /api/v1/organizations/{orgId})
	DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID)
	// Get an organization
	// (GET /api/v1/organizations/{orgId})
	GetOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID)
	// Update organization settings (name only; slug is immutable)
	// (PATCH /api/v1/organizations/{orgId})
	UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID)
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Verify credentials
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke the current session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a password-reset email
// (POST /api/v1/auth/password-reset)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set a new password using a reset token
// (POST /api/v1/auth/password-reset/confirm)
func (_ Unimplemented) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a local account (sends a verification email)
// (POST /api/v1/auth/signup)
func (_ Unimplemented) Signup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify an email address with a token
// (POST /api/v1/auth/verify-email)
func (_ Unimplemented) VerifyEmail(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List organizations
// (GET /api/v1/organizations)
func (_ Unimplemented) ListOrganizations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organization
// (POST /api/v1/organizations)
func (_ Unimplemented) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete an organization
// (DELETE /api/v1/organizations/{orgId})
func (_ Unimplemented) DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an organization
// (GET /api/v1/organizations/{orgId})
func (_ Unimplemented) GetOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update organization settings (name only; slug is immutable)
// (PATCH /api/v1/organizations/{orgId})
func (_ Unimplemented) UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrganization operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrganization operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", chi.URLParam(r, "orgId"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password-reset", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/signup", wrapper.Signup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/verify-email", wrapper.VerifyEmail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations", wrapper.ListOrganizations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/organizations", wrapper.CreateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/organizations/{orgId}", wrapper.DeleteOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations/{orgId}", wrapper.GetOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/organizations/{orgId}", wrapper.UpdateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})

	return r
}

type ErrorResponseHeaders struct {
	XRequestId string
}
type ErrorJSONResponse struct {
	Body Error

	Headers ErrorResponseHeaders
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	XRequestId string
}

type Login200JSONResponse struct {
	Body    AuthUser
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type LogindefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response LogindefaultJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	XRequestId string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(204)
	return nil
}

type LogoutdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response LogoutdefaultJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RequestPasswordResetRequestObject struct {
	Body *RequestPasswordResetJSONRequestBody
}

type RequestPasswordResetResponseObject interface {
	VisitRequestPasswordResetResponse(w http.ResponseWriter) error
}

type RequestPasswordReset202ResponseHeaders struct {
	XRequestId string
}

type RequestPasswordReset202JSONResponse struct {
	Body    GenericMessage
	Headers RequestPasswordReset202ResponseHeaders
}

func (response RequestPasswordReset202JSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response.Body)
}

type RequestPasswordResetdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response RequestPasswordResetdefaultJSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ConfirmPasswordResetRequestObject struct {
	Body *ConfirmPasswordResetJSONRequestBody
}

type ConfirmPasswordResetResponseObject interface {
	VisitConfirmPasswordResetResponse(w http.ResponseWriter) error
}

type ConfirmPasswordReset200ResponseHeaders struct {
	XRequestId string
}

type ConfirmPasswordReset200JSONResponse struct {
	Body    GenericMessage
	Headers ConfirmPasswordReset200ResponseHeaders
}

func (response ConfirmPasswordReset200JSONResponse) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ConfirmPasswordResetdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response ConfirmPasswordResetdefaultJSONResponse) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup202ResponseHeaders struct {
	XRequestId string
}

type Signup202JSONResponse struct {
	Body    GenericMessage
	Headers Signup202ResponseHeaders
}

func (response Signup202JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response.Body)
}

type SignupdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response SignupdefaultJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type VerifyEmailRequestObject struct {
	Body *VerifyEmailJSONRequestBody
}

type VerifyEmailResponseObject interface {
	VisitVerifyEmailResponse(w http.ResponseWriter) error
}

type VerifyEmail200ResponseHeaders struct {
	XRequestId string
}

type VerifyEmail200JSONResponse struct {
	Body    GenericMessage
	Headers VerifyEmail200ResponseHeaders
}

func (response VerifyEmail200JSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type VerifyEmaildefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response VerifyEmaildefaultJSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListOrganizationsRequestObject struct {
}

type ListOrganizationsResponseObject interface {
	VisitListOrganizationsResponse(w http.ResponseWriter) error
}

type ListOrganizations200ResponseHeaders struct {
	XRequestId string
}

type ListOrganizations200JSONResponse struct {
	Body    []Organization
	Headers ListOrganizations200ResponseHeaders
}

func (response ListOrganizations200JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListOrganizationsdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response ListOrganizationsdefaultJSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateOrganizationRequestObject struct {
	Body *CreateOrganizationJSONRequestBody
}

type CreateOrganizationResponseObject interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization201ResponseHeaders struct {
	XRequestId string
}

type CreateOrganization201JSONResponse struct {
	Body    Organization
	Headers CreateOrganization201ResponseHeaders
}

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response CreateOrganizationdefaultJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteOrganizationRequestObject struct {
	OrgId openapi_types.UUID `json:"orgId"`
}

type DeleteOrganizationResponseObject interface {
	VisitDeleteOrganizationResponse(w http.ResponseWriter) error
}

type DeleteOrganization204ResponseHeaders struct {
	XRequestId string
}

type DeleteOrganization204Response struct {
	Headers DeleteOrganization204ResponseHeaders
}

func (response DeleteOrganization204Response) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(204)
	return nil
}

type DeleteOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response DeleteOrganizationdefaultJSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOrganizationRequestObject struct {
	OrgId openapi_types.UUID `json:"orgId"`
}

type GetOrganizationResponseObject interface {
	VisitGetOrganizationResponse(w http.ResponseWriter) error
}

type GetOrganization200ResponseHeaders struct {
	XRequestId string
}

type GetOrganization200JSONResponse struct {
	Body    Organization
	Headers GetOrganization200ResponseHeaders
}

func (response GetOrganization200JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response GetOrganizationdefaultJSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateOrganizationRequestObject struct {
	OrgId openapi_types.UUID `json:"orgId"`
	Body  *UpdateOrganizationJSONRequestBody
}

type UpdateOrganizationResponseObject interface {
	VisitUpdateOrganizationResponse(w http.ResponseWriter) error
}

type UpdateOrganization200ResponseHeaders struct {
	XRequestId string
}

type UpdateOrganization200JSONResponse struct {
	Body    Organization
	Headers UpdateOrganization200ResponseHeaders
}

func (response UpdateOrganization200JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateOrganizationdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response UpdateOrganizationdefaultJSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200ResponseHeaders struct {
	XRequestId string
}

type GetHealth200JSONResponse struct {
	Body    HealthResponse
	Headers GetHealth200ResponseHeaders
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthdefaultJSONResponse struct {
	Body       Error
	Headers    ErrorResponseHeaders
	StatusCode int
}

func (response GetHealthdefaultJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-Id", fmt.Sprint(response.Headers.XRequestId))
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Verify credentials
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current session
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Request a password-reset email
	// (POST /api/v1/auth/password-reset)
	RequestPasswordReset(ctx context.Context, request RequestPasswordResetRequestObject) (RequestPasswordResetResponseObject, error)
	// Set a new password using a reset token
	// (POST /api/v1/auth/password-reset/confirm)
	ConfirmPasswordReset(ctx context.Context, request ConfirmPasswordResetRequestObject) (ConfirmPasswordResetResponseObject, error)
	// Create a local account (sends a verification email)
	// (POST /api/v1/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)
	// Verify an email address with a token
	// (POST /api/v1/auth/verify-email)
	VerifyEmail(ctx context.Context, request VerifyEmailRequestObject) (VerifyEmailResponseObject, error)
	// List organizations
	// (GET /api/v1/organizations)
	ListOrganizations(ctx context.Context, request ListOrganizationsRequestObject) (ListOrganizationsResponseObject, error)
	// Create an organization
	// (POST /api/v1/organizations)
	CreateOrganization(ctx context.Context, request CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error)
	// Soft-delete an organization
	// (DELETE /api/v1/organizations/{orgId})
	DeleteOrganization(ctx context.Context, request DeleteOrganizationRequestObject) (DeleteOrganizationResponseObject, error)
	// Get an organization
	// (GET /api/v1/organizations/{orgId})
	GetOrganization(ctx context.Context, request GetOrganizationRequestObject) (GetOrganizationResponseObject, error)
	// Update organization settings (name only; slug is immutable)
	// (PATCH /api/v1/organizations/{orgId})
	UpdateOrganization(ctx context.Context, request UpdateOrganizationRequestObject) (UpdateOrganizationResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestPasswordReset operation middleware
func (sh *strictHandler) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	var request RequestPasswordResetRequestObject

	var body RequestPasswordResetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestPasswordReset(ctx, request.(RequestPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestPasswordReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestPasswordResetResponseObject); ok {
		if err := validResponse.VisitRequestPasswordResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmPasswordReset operation middleware
func (sh *strictHandler) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	var request ConfirmPasswordResetRequestObject

	var body ConfirmPasswordResetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmPasswordReset(ctx, request.(ConfirmPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmPasswordReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConfirmPasswordResetResponseObject); ok {
		if err := validResponse.VisitConfirmPasswordResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Signup operation middleware
func (sh *strictHandler) Signup(w http.ResponseWriter, r *http.Request) {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx, request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyEmail operation middleware
func (sh *strictHandler) VerifyEmail(w http.ResponseWriter, r *http.Request) {
	var request VerifyEmailRequestObject

	var body VerifyEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyEmail(ctx, request.(VerifyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyEmailResponseObject); ok {
		if err := validResponse.VisitVerifyEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrganizations operation middleware
func (sh *strictHandler) ListOrganizations(w http.ResponseWriter, r *http.Request) {
	var request ListOrganizationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizations(ctx, request.(ListOrganizationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationsResponseObject); ok {
		if err := validResponse.VisitListOrganizationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganization operation middleware
func (sh *strictHandler) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	var request CreateOrganizationRequestObject

	var body CreateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganization(ctx, request.(CreateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrganization operation middleware
func (sh *strictHandler) DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	var request DeleteOrganizationRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrganization(ctx, request.(DeleteOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrganizationResponseObject); ok {
		if err := validResponse.VisitDeleteOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrganization operation middleware
func (sh *strictHandler) GetOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	var request GetOrganizationRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrganization(ctx, request.(GetOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrganizationResponseObject); ok {
		if err := validResponse.VisitGetOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrganization operation middleware
func (sh *strictHandler) UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId openapi_types.UUID) {
	var request UpdateOrganizationRequestObject

	request.OrgId = orgId

	var body UpdateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrganization(ctx, request.(UpdateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateOrganizationResponseObject); ok {
		if err := validResponse.VisitUpdateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xab3PbuPH+Kjv83Yv4V/2L0+m18qvUuct5mjYZO3ftTOzaMLEicQYBFljKVjKe6Yfo",
	"J+wn6SxASaRE2ZZru3pliyKw2GefXTwL6FuS2qK0Bg35ZPwtyVFIdOHfY/xHhZ6OJH+Q6FOnSlLWJOPk",
	"0DqHWvAnOHoHE+uAcuXBxSEHILS3IMoShfOgDHh0U3SgbeYHSS/h95RDmYzJVdhLfJpjIdgOzUpMxokn",
	"p0yW3N7e8su+tMZjWNQPzlnH/6TWEBrif0VZapWG1Qx/9bzAb40Zv3M4ScbJ/w2Xjg7jt34YZwtW2g6G",
	"L2BumZfcAOZv/RqafsSmy0L9+nAJ4m0wU1vmYW8ryn/2GLwRUio2LfQnZ0t0pNjdidAee0nZePQtwUIo",
	"zf9MrCsEJeP6SW8Vu1784nyKTk0Uyga8l9ZqFIbfUbI1V1UpuT7VbTNkX5LwytzqipGzxWB7+SumxDYO",
	"HQrCjy4TRn0Ncaph2dJ1Iwrkv4W4+YAmozwZ749GvaRQZv75dQcMXlfZyrDfvVkdVQoidBz7v38R/a+j",
	"/h/OfvOqv/h37/+/uxeWsLzaXBcMC+7e6XKbiCckjBROAgZGopmitiWGlMMpuhkYa/r7NzdLssJhbj0a",
	"sJxxl8LhqTn+8RC+//3oe/AWKEdIG/l7USftuZIXoDwImCjnqZ9q4T1MFGoZxpx8entqhJFw+OEIUmHA",
	"V24iUgSpHKakZwdwkVqJYRJP4lLHVZbOZk4UhSCVQi6M1Mpkg1OTrBH7QfC0x7DB9fJ0Eqz3oBBprgz2",
	"HQoZ1hNB5EGc0ngjilJzjIyl84mtjOzKIokklPbrZn5kbPoap6jZy0uNhYdXOMgGMBVayYjvRChdOfR7",
	"bFIRFv5BVeldsMr26wUJ58SMPxfovcg63P6pKoRpOHtTamHCIgZdfi3jfl+BP4BCUJqDyIQynlar+d1Z",
	"EUK0XPV6Yqy8H2mwMX9qXLajSWDxupfvLBFKKAXlQDEz7GSCRiqTReb34DpHA/UOc6mxE8mNEflrLojT",
	"4dpZk8G1Yju8T4a574duM2a95D0adCr989L0Fng0Fvz4FfyEQlN+XJedLVfwcPKtqYvOEDAlVdoRgmMs",
	"rSMOaP0KcJlupz9VxuBNX5Sqc2oSVHWk/wc1RYM+FDuqQiagqQqGzV41ENsAbT3tculdGH+wmXrkZrlZ",
	"JzT2wTf7ow6PS+H9tXWya6+926m5icUMXU41hcC29T4oCXkuqOWZFIR9UmH7XfPmQQqntxAXG+XD2hdV",
	"KbdcTJeOaqqGXtPBloEuHD/VIB+jRzq0ZqJc8Tiu3BXwpkza78CN7BWarVXZChJxknt40/L3hZOik+dd",
	"izxRmanKF0/ZTdJ4q9y+O9SPSfXPHNfHgfGEvOpa2c8htx7Tk7R3gY9Gz4Jy4AjwXl9UQX0ehIec1RA2",
	"/BuUIAhCfteK7Amam64OpFNheUwrp2h2whpzrp3tlULuQvmTYmfio3lRmm+M5x69Z2+XWrRUf8JZbJyV",
	"mdiuPdyQs7rPEhTh7aejsI1/DvMNlB3AZ97RfYkpwxOgUibTCN5WLmUdBuQqysenhr98b+eik1fgh6GP",
	"QOeBGxJ+4fOsxJNgH1Kt0BAIh5CxSOISChNnC1B0al5dFOJq+c3FXi/MIZ2aUNDqcTWXldISVl7upzmm",
	"Vxd7sXshRUE9RKfYx6SXTNH5iMBo8HowYqbZEg1Li3HyZjAavAkpQ3kIwVCUajh9PRQV5UPNe32oxjay",
	"cKWp2R+8hrrN9swjiYaU0P4ATvYH+4Ch51I+xxrPGDSIMWW+MdsC+Y4ky5dgbtEG/NHK2ZOdq7Rky22b",
	"peQqXD3V2R+Nnsz24lil41jncIlabNGe6mSHDU1EpWnTqIW7izOnZU4m4y9nvcRXRSHcLBknv3CQZ80Q",
	"M9tE5jnFmSrJGQ9fJY+taDN7jiQWpWV04d///BekOpzMxbMA5kdIAodTe7VCHzWB0qFHQ50UYqNrwfxt",
	"h1i2WYYSbEU7Cflx8DziUTnHMDWK3t3QzzfAPsPUCkEbrXr1LRXzTPnXqZQelIf7T7aGlQa1IxvfpimW",
	"hHIA9bvg0FeawGEmnNTcW9kJd+CUc+XPEYLoALxRnvyOEinMDALatIDFIe02ZBqmUdVvJlUt+1+cVCvt",
	"xgvX+Pu5NV8s1D3UTpLlBJkoBq8XZIGKZRAIiKSZt0X3kMaHnmMzSWJP8ky0aDc8O1xkjpEqZ+rdjcV6",
	"1q468zpjHRhLjXJzLTwI7VDIGZcm5QndjjIq3rSAAG1ToUGkqa0MwSuPRnoQtX6MUEfv9u6nVxg06y+6",
	"026SRdXyQ13mnoNprWZy5yrOL/UN2C5LSlEHHYSUjrfXcCQtHlBnbKNRDn5lSF1Hop5igrXeD094Tpaz",
	"aejHKo8OLlFbk3kg26EtlaePLaP/ZXQfdPXSOppcu3tZD3prhf/byC9izci18W9Etv387La3oV+IhYT7",
	"69ZUAzgyMb4lGsB4SlLfaYTemQl1ai6sy861KhSdOxRpjvICrOG23rSpUUu5eFiChtCVTvm6/T41Qmt7",
	"7aGoNKlSY+y7VwTQ2t3yM1WfzZfYDypFr59sIW2OrnPyMzcx8Ri5HbvdoOd8i2oT6w6KbqpCw2/WZUfy",
	"NpJXI+H6pvQuPF9jx33dahwmdwSxEzuhfvRwC9h68xLdRuQ90t1wjF6UqDtI0PesyreAuRROFEhh1V/q",
	"g9RSUL48Rg08vfNnT/f9/uYsHBqm+Xo818+xn6n+bT4wf2Ep9hBa1V3fLtIr4tjeBT0SKVZCr8ItgjV6",
	"drC4O1BFfaWwd0+RzMOF/NeN6ixehXsonU1Z/On6AnsAf7GAN4TOCA0SSzQSTap4+3cI4dA7FsO1UhJ/",
	"A/CcRWTlVwYb4j2/21fcqakp7qQIX/xgoHT2EhvB9DNPWHAU26PbdzRfzrgMxGuQWGpWLghEgX3rVKYM",
	"N3xuihIuMVf1DQnKDMFkytwwjyqnk3EyTG7Pbv8TAAD//+LPuloDKgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
