#!/bin/sh
# Tunnex.io — zero-build installer (S6.6).
#
#   curl -fsSL https://raw.githubusercontent.com/iotunnex/tunnex/main/deploy/install.sh | sh
#
# Brings up a working Tunnex deployment from PREBUILT images — no source build, no file edits. It
# asks exactly two things (public address; SMTP or skip), generates the DB secret, pins a real
# release version, writes a CLEAN .env, and starts the stack. Config lives in ./tunnex/.env; the
# compose file (deploy/tunnex.yml) is never hand-edited.
set -eu

REPO="iotunnex/tunnex"
RAW="https://raw.githubusercontent.com/${REPO}"
API="https://api.github.com/repos/${REPO}"
DIR="${TUNNEX_DIR:-tunnex}"

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }
# ask reads from the TERMINAL even under `curl | sh` (stdin is the pipe).
ask() {
	printf '%s' "$1" >/dev/tty
	IFS= read -r reply </dev/tty || die "no input (run the script interactively, not fully piped)"
	printf '%s' "$reply"
}

# ── 0. prerequisites ─────────────────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is required — install Docker Engine + the Compose plugin, then re-run."
docker compose version >/dev/null 2>&1 || die "The Docker Compose v2 plugin is required (\`docker compose\`)."
command -v curl >/dev/null 2>&1 || die "curl is required."
command -v openssl >/dev/null 2>&1 || die "openssl is required (secret generation)."

# ── 1. pin a real RELEASE version (never :latest for a real deploy — reproducible + revertible) ──
VERSION="${TUNNEX_VERSION:-}"
if [ -z "$VERSION" ]; then
	VERSION="$(curl -fsSL "${API}/releases/latest" 2>/dev/null | grep -m1 '"tag_name"' | sed -E 's/.*"tag_name" *: *"([^"]+)".*/\1/')"
fi
[ -n "$VERSION" ] || die "could not resolve a released Tunnex version. To track main instead, re-run with TUNNEX_VERSION=latest."
say ">> Installing Tunnex ${VERSION}"

# ── 2. public address — REJECT loopback (POC item 3: localhost email/WG on a remote box) ─────────
while :; do
	ADDR="$(ask 'Public address your users + gateways reach (DNS name or public IP, e.g. vpn.acme.com): ')"
	case "$ADDR" in
	'' | localhost | localhost:* | 127.* | ::1 | 0.0.0.0 | *://*)
		say "!! '${ADDR}' is not a usable public address (loopback/empty, or includes a scheme). Enter the bare"
		say "   DNS name or public IP the machine is reachable at — email verify/reset links and the WireGuard"
		say "   endpoint depend on it. (Pure-local dev uses the repo's docker-compose.yml, not this installer.)"
		;;
	*) break ;;
	esac
done

# ── 3. SMTP — configure or skip ─────────────────────────────────────────────────────────────────
SMTP_HOST=''
SMTP_PORT=''
SMTP_FROM=''
SMTP_USERNAME=''
SMTP_PASSWORD=''
case "$(ask 'Configure SMTP now for email (verify / reset / invite)? [y/N]: ')" in
y | Y | yes | YES)
	SMTP_HOST="$(ask '  SMTP host: ')"
	SMTP_PORT="$(ask '  SMTP port [587]: ')"
	SMTP_PORT="${SMTP_PORT:-587}"
	SMTP_USERNAME="$(ask '  SMTP username: ')"
	SMTP_PASSWORD="$(ask '  SMTP password: ')"
	SMTP_FROM="$(ask "  From address [no-reply@${ADDR}]: ")"
	SMTP_FROM="${SMTP_FROM:-no-reply@${ADDR}}"
	;;
*)
	say ">> SMTP skipped — email features are disabled (local sign-in still works; enable later by"
	say "   setting SMTP_* in .env and re-running \`docker compose -f tunnex.yml up -d\`)."
	;;
esac

# ── 4. secrets ──────────────────────────────────────────────────────────────────────────────────
PG_PASS="$(openssl rand -hex 24)"

# ── 5. workspace + the VERSIONED compose (matches the pinned images) ─────────────────────────────
mkdir -p "$DIR"
cd "$DIR"
curl -fsSL "${RAW}/${VERSION}/deploy/tunnex.yml" -o tunnex.yml || die "could not download deploy/tunnex.yml for ${VERSION}"

# ── 6. write a CLEAN .env (write the WHOLE file — NEVER append; duplicate keys make compose ──────
#      silently use the FIRST value — the trap that bit the POC). Back up any existing one. ────────
if [ -f .env ]; then
	cp .env ".env.bak.$(date +%Y%m%d%H%M%S)"
	say ">> Backed up your existing .env"
fi
umask 077
cat >.env.new <<EOF
# Tunnex deployment config — generated by install.sh. Safe to edit these values; do NOT hand-edit
# tunnex.yml. Upgrade: bump TUNNEX_VERSION to a newer release tag, then \`docker compose -f tunnex.yml pull && up -d\`.
TUNNEX_VERSION=${VERSION}
TUNNEX_LOG_LEVEL=info
APP_BASE_URL=http://${ADDR}
TUNNEX_NODE_ENDPOINT=${ADDR}:51820
POSTGRES_USER=tunnex
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=tunnex
DATABASE_URL=postgres://tunnex:${PG_PASS}@postgres:5432/tunnex?sslmode=disable
REDIS_URL=redis://redis:6379/0
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_FROM=${SMTP_FROM}
SMTP_USERNAME=${SMTP_USERNAME}
SMTP_PASSWORD=${SMTP_PASSWORD}
EOF
mv .env.new .env

# ── 7. pull + start ─────────────────────────────────────────────────────────────────────────────
say ">> Pulling images and starting the stack…"
docker compose -f tunnex.yml pull
docker compose -f tunnex.yml up -d --wait

# ── 8. NEXT STEPS (the customer's first experience — a real hand-off, not an echo) ───────────────
say ''
say '════════════════════════════════════════════════════════════════════════════'
say " Tunnex ${VERSION} is running."
say ''
say "   1. Open the dashboard:   http://${ADDR}/"
say '   2. Sign up — you will be guided to create your first organization.'
say '   3. Enroll a gateway:     Dashboard → Gateways → “Generate join token”.'
say '      Copy the ONE command it shows and run it in this folder to bring the'
say '      gateway online (it re-creates the node-agent with your join token).'
say ''
say "   Config:   $(pwd)/.env       (edit values here; never hand-edit tunnex.yml)"
say '   Upgrade:  set TUNNEX_VERSION to a newer tag in .env, then:'
say '             docker compose -f tunnex.yml pull && docker compose -f tunnex.yml up -d'
say '════════════════════════════════════════════════════════════════════════════'
