// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAccessEvent = `-- name: InsertAccessEvent :execrows
INSERT INTO access_events (
    id, org_id, seq, node_id, occurred_at, decision, rule_id,
    src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id,
    protocol, dst_port, deny_count, window_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17
)
ON CONFLICT (org_id, seq) DO NOTHING
`

type InsertAccessEventParams struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	Seq           int64              `json:"seq"`
	NodeID        pgtype.UUID        `json:"node_id"`
	OccurredAt    time.Time          `json:"occurred_at"`
	Decision      string             `json:"decision"`
	RuleID        pgtype.UUID        `json:"rule_id"`
	SrcDeviceID   pgtype.UUID        `json:"src_device_id"`
	SrcUserID     pgtype.UUID        `json:"src_user_id"`
	SrcIp         string             `json:"src_ip"`
	DstIp         string             `json:"dst_ip"`
	DstResourceID pgtype.UUID        `json:"dst_resource_id"`
	DstGroupID    pgtype.UUID        `json:"dst_group_id"`
	Protocol      string             `json:"protocol"`
	DstPort       *int32             `json:"dst_port"`
	DenyCount     int32              `json:"deny_count"`
	WindowEnd     pgtype.Timestamptz `json:"window_end"`
}

// Idempotent on (org_id, seq) so a replayed ingest batch can't double-insert. The id is
// app-generated (uuid v7) so the SAME id identifies the row in BOTH the PG hot-window and
// the JSONL source-of-truth stream.
func (q *Queries) InsertAccessEvent(ctx context.Context, arg InsertAccessEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAccessEvent,
		arg.ID,
		arg.OrgID,
		arg.Seq,
		arg.NodeID,
		arg.OccurredAt,
		arg.Decision,
		arg.RuleID,
		arg.SrcDeviceID,
		arg.SrcUserID,
		arg.SrcIp,
		arg.DstIp,
		arg.DstResourceID,
		arg.DstGroupID,
		arg.Protocol,
		arg.DstPort,
		arg.DenyCount,
		arg.WindowEnd,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccessDenies = `-- name: ListAccessDenies :many
SELECT id, org_id, seq, node_id, occurred_at, decision, rule_id, src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id, protocol, dst_port, deny_count, window_end, created_at FROM access_events
WHERE org_id = $1
  AND decision <> 'allow'
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAccessDeniesParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforeID        uuid.UUID `json:"before_id"`
	PageLimit       int32     `json:"page_limit"`
}

// The security-focused feed: deny + deny_aggregate + terminated only, same keyset shape.
func (q *Queries) ListAccessDenies(ctx context.Context, arg ListAccessDeniesParams) ([]AccessEvent, error) {
	rows, err := q.db.Query(ctx, listAccessDenies,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessEvent{}
	for rows.Next() {
		var i AccessEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Seq,
			&i.NodeID,
			&i.OccurredAt,
			&i.Decision,
			&i.RuleID,
			&i.SrcDeviceID,
			&i.SrcUserID,
			&i.SrcIp,
			&i.DstIp,
			&i.DstResourceID,
			&i.DstGroupID,
			&i.Protocol,
			&i.DstPort,
			&i.DenyCount,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessEvents = `-- name: ListAccessEvents :many
SELECT id, org_id, seq, node_id, occurred_at, decision, rule_id, src_device_id, src_user_id, src_ip, dst_ip, dst_resource_id, dst_group_id, protocol, dst_port, deny_count, window_end, created_at FROM access_events
WHERE org_id = $1
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAccessEventsParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforeID        uuid.UUID `json:"before_id"`
	PageLimit       int32     `json:"page_limit"`
}

// Keyset page, newest-first, scoped by org. Expanded (created_at, id) < (cursor) predicate
// (row-value form confuses sqlc's type inference for the id cursor). First page passes a
// far-future created_at + a max uuid so the whole feed is < the cursor. Uses
// access_events_org_created_id_idx.
func (q *Queries) ListAccessEvents(ctx context.Context, arg ListAccessEventsParams) ([]AccessEvent, error) {
	rows, err := q.db.Query(ctx, listAccessEvents,
		arg.OrgID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessEvent{}
	for rows.Next() {
		var i AccessEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Seq,
			&i.NodeID,
			&i.OccurredAt,
			&i.Decision,
			&i.RuleID,
			&i.SrcDeviceID,
			&i.SrcUserID,
			&i.SrcIp,
			&i.DstIp,
			&i.DstResourceID,
			&i.DstGroupID,
			&i.Protocol,
			&i.DstPort,
			&i.DenyCount,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAccessEventSeqForOrg = `-- name: MaxAccessEventSeqForOrg :one
SELECT COALESCE(MAX(seq), 0)::bigint AS max_seq FROM access_events WHERE org_id = $1
`

// The current high-water seq for an org — the ingest resumes the monotonic counter from
// here after a restart so the per-org sequence never rewinds (gap-detection integrity).
func (q *Queries) MaxAccessEventSeqForOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, maxAccessEventSeqForOrg, orgID)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const sweepAccessEventsByAge = `-- name: SweepAccessEventsByAge :execrows
DELETE FROM access_events WHERE created_at < $1
`

// lint:cross-org — retention housekeeping runs across ALL orgs by INGEST age (created_at,
// not the agent-clock occurred_at, so agent skew can't extend retention). The JSONL stream
// keeps the full record; PG is a bounded cache, so this delete is lossless for export.
func (q *Queries) SweepAccessEventsByAge(ctx context.Context, olderThan time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepAccessEventsByAge, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepAccessEventsOverCap = `-- name: SweepAccessEventsOverCap :execrows
DELETE FROM access_events AS target
WHERE target.org_id = $1
  AND target.id NOT IN (
    SELECT ae.id FROM access_events ae
    WHERE ae.org_id = $1
    ORDER BY ae.created_at DESC, ae.id DESC
    LIMIT $2
  )
`

type SweepAccessEventsOverCapParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	KeepNewest int32     `json:"keep_newest"`
}

// Per-org row cap: keep the newest keep_newest rows for the org, delete the rest. Protects
// the disk when one org is noisy without touching quiet orgs.
func (q *Queries) SweepAccessEventsOverCap(ctx context.Context, arg SweepAccessEventsOverCapParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepAccessEventsOverCap, arg.OrgID, arg.KeepNewest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
