// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertDeviceStatus = `-- name: UpsertDeviceStatus :batchexec
INSERT INTO device_status (device_id, last_handshake_at, rx_bytes, tx_bytes, updated_at)
SELECT d.id, $1, $2, $3, now()
FROM devices d
WHERE d.node_id = $4 AND d.public_key = $5
  AND d.status = 'active' AND d.deleted_at IS NULL
ON CONFLICT (device_id) DO UPDATE
SET last_handshake_at = EXCLUDED.last_handshake_at,
    rx_bytes = EXCLUDED.rx_bytes,
    tx_bytes = EXCLUDED.tx_bytes,
    updated_at = now()
`

type UpsertDeviceStatusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertDeviceStatusParams struct {
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         int64              `json:"rx_bytes"`
	TxBytes         int64              `json:"tx_bytes"`
	NodeID          uuid.UUID          `json:"node_id"`
	PublicKey       string             `json:"public_key"`
}

// lint:cross-org — keyed by node_id (agent is cert-authorized) + pubkey. Batched
// (pgx.Batch) so a whole report is a single round-trip; no per-peer write
// amplification and the write lands on the lean status table, not the devices
// row. Maps pubkey->active device on this node; an unknown pubkey is a no-op.
// rx/tx are raw gauges.
func (q *Queries) UpsertDeviceStatus(ctx context.Context, arg []UpsertDeviceStatusParams) *UpsertDeviceStatusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LastHandshakeAt,
			a.RxBytes,
			a.TxBytes,
			a.NodeID,
			a.PublicKey,
		}
		batch.Queue(upsertDeviceStatus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertDeviceStatusBatchResults{br, len(arg), false}
}

func (b *UpsertDeviceStatusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertDeviceStatusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
