// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveDevice = `-- name: ApproveDevice :one
UPDATE devices
SET status = 'active', approved_by = $3, updated_at = now()
WHERE id = $1 AND org_id = $2 AND status = 'pending' AND deleted_at IS NULL
RETURNING user_id
`

type ApproveDeviceParams struct {
	ID         uuid.UUID   `json:"id"`
	OrgID      uuid.UUID   `json:"org_id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

// S7.3: pending -> active, recording the approver (approved_by). Only a PENDING device
// can be approved (pgx.ErrNoRows => not pending: already active / rejected / wrong org).
// Returns the owner so the caller can distinguish self-approval for the audit.
func (q *Queries) ApproveDevice(ctx context.Context, arg ApproveDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, approveDevice, arg.ID, arg.OrgID, arg.ApprovedBy)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countActiveDevicesForOrg = `-- name: CountActiveDevicesForOrg :one
SELECT count(*) FROM devices
WHERE org_id = $1 AND status = 'active' AND deleted_at IS NULL
`

// Grandfathered count when flipping device_approval off->on (best-effort blast radius,
// S7.3 D4 — existing active devices stay active, not retro-pended).
func (q *Queries) CountActiveDevicesForOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDevicesForOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevicesForUserCap = `-- name: CountDevicesForUserCap :one
SELECT count(*) FROM devices
WHERE org_id = $1 AND user_id = $2 AND status IN ('active', 'pending') AND deleted_at IS NULL
`

type CountDevicesForUserCapParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

// The per-user device cap counts ACTIVE + PENDING (S7.3 finding #1): a pending device
// reserves a real pool /32 and is a real enrollment, so excluding it let a user create
// unbounded pending devices (cap bypass on approve + an org-pool DoS). CONVENTION: pending
// is EXCLUDED from enforcement but INCLUDED in resource accounting (caps, pools, sweeps).
func (q *Queries) CountDevicesForUserCap(ctx context.Context, arg CountDevicesForUserCapParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesForUserCap, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (org_id, user_id, node_id, name, platform, public_key, assigned_ip, full_tunnel, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, user_id, node_id, name, platform, public_key, assigned_ip, status, created_at, updated_at, revoked_at, deleted_at, full_tunnel, approved_by
`

type CreateDeviceParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	UserID     uuid.UUID `json:"user_id"`
	NodeID     uuid.UUID `json:"node_id"`
	Name       string    `json:"name"`
	Platform   string    `json:"platform"`
	PublicKey  string    `json:"public_key"`
	AssignedIp *string   `json:"assigned_ip"`
	FullTunnel bool      `json:"full_tunnel"`
	Status     string    `json:"status"`
}

// status is 'active' normally, or 'pending' when the org requires device approval
// (S7.3). A pending device holds its assigned_ip from creation (excluded from every
// status='active' reader EXCEPT the allocator, which counts its IP as in-flight).
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.OrgID,
		arg.UserID,
		arg.NodeID,
		arg.Name,
		arg.Platform,
		arg.PublicKey,
		arg.AssignedIp,
		arg.FullTunnel,
		arg.Status,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.NodeID,
		&i.Name,
		&i.Platform,
		&i.PublicKey,
		&i.AssignedIp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.DeletedAt,
		&i.FullTunnel,
		&i.ApprovedBy,
	)
	return i, err
}

const deleteDeviceStatus = `-- name: DeleteDeviceStatus :exec
DELETE FROM device_status WHERE device_id = $1
`

// lint:cross-org — keyed by device_id (the caller already authorized the device
// via its org). Clears a device's live status (on revoke) so a revoked device
// never reports stale online/handshake via the API.
func (q *Queries) DeleteDeviceStatus(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceStatus, deviceID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, org_id, user_id, node_id, name, platform, public_key, assigned_ip, status, created_at, updated_at, revoked_at, deleted_at, full_tunnel, approved_by FROM devices
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetDeviceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.OrgID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.NodeID,
		&i.Name,
		&i.Platform,
		&i.PublicKey,
		&i.AssignedIp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.DeletedAt,
		&i.FullTunnel,
		&i.ApprovedBy,
	)
	return i, err
}

const getOrgNode = `-- name: GetOrgNode :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities FROM nodes
WHERE id = $1 AND org_id = $2 AND status = 'active'
`

type GetOrgNodeParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Verifies a node belongs to the org (id+org scoped) before a device attaches to it.
func (q *Queries) GetOrgNode(ctx context.Context, arg GetOrgNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, getOrgNode, arg.ID, arg.OrgID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
	)
	return i, err
}

const listActiveDeviceAllocations = `-- name: ListActiveDeviceAllocations :many
SELECT id, name, assigned_ip FROM devices
WHERE org_id = $1 AND assigned_ip IS NOT NULL AND status IN ('active', 'pending') AND deleted_at IS NULL
ORDER BY assigned_ip
`

type ListActiveDeviceAllocationsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	AssignedIp *string   `json:"assigned_ip"`
}

// The org's live tunnel allocations (flat pool, across all nodes) WITH the owning
// device (id, name). The SINGLE definition of "live allocation" — used by BOTH
// device-create's lowest-free choice AND resize's orphan check/409 objects, so
// there are no two filtered reads to drift apart. Read under the org advisory
// lock so allocation and resize serialize on the same snapshot.
//
// INCLUDES 'pending' (S7.3): a pending device HOLDS its assigned_ip from creation, so it
// is IN-FLIGHT — create must not hand its IP to another device (silent duplicate; the
// org_ip unique index is likewise widened to active+pending), and resize's orphan check
// must see it (else a shrink silently strands a pending device's allocation). Revoked/
// rejected devices have assigned_ip=NULL and never appear.
func (q *Queries) ListActiveDeviceAllocations(ctx context.Context, orgID uuid.UUID) ([]ListActiveDeviceAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceAllocations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDeviceAllocationsRow{}
	for rows.Next() {
		var i ListActiveDeviceAllocationsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AssignedIp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveFullTunnelDevices = `-- name: ListActiveFullTunnelDevices :many
SELECT d.id, d.user_id, d.name, d.assigned_ip
FROM devices d
JOIN users u ON u.id = d.user_id
JOIN memberships mem ON mem.org_id = d.org_id AND mem.user_id = d.user_id
WHERE d.org_id = $1
  AND d.status = 'active' AND d.deleted_at IS NULL
  AND u.status = 'active' AND u.deleted_at IS NULL
  AND d.full_tunnel
ORDER BY d.name
`

type ListActiveFullTunnelDevicesRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Name       string    `json:"name"`
	AssignedIp *string   `json:"assigned_ip"`
}

// S7.2 decision 2a: the devices whose internet egress is governed by policy once the
// org enters enforcing mode -- enumerated (count + names) in the mode-enable response
// so the warn-and-confirm shows real blast radius. Owner must be a CURRENT org member
// (the F1 convention: policy-input queries re-verify membership, not just status).
func (q *Queries) ListActiveFullTunnelDevices(ctx context.Context, orgID uuid.UUID) ([]ListActiveFullTunnelDevicesRow, error) {
	rows, err := q.db.Query(ctx, listActiveFullTunnelDevices, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveFullTunnelDevicesRow{}
	for rows.Next() {
		var i ListActiveFullTunnelDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AssignedIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePeersForNode = `-- name: ListActivePeersForNode :many
SELECT d.public_key, d.assigned_ip
FROM devices d
JOIN users u ON u.id = d.user_id
WHERE d.node_id = $1
  AND d.status = 'active' AND d.deleted_at IS NULL
  AND u.status = 'active' AND u.deleted_at IS NULL
ORDER BY d.created_at
`

type ListActivePeersForNodeRow struct {
	PublicKey  string  `json:"public_key"`
	AssignedIp *string `json:"assigned_ip"`
}

// lint:cross-org — keyed by node_id after mTLS cert authorization (the agent
// fetches the peers for its own node). A peer is present only while BOTH the
// device is active AND its owning user is active — so deactivating a user drops
// their peers from every node's desired state (and reactivation restores them).
func (q *Queries) ListActivePeersForNode(ctx context.Context, nodeID uuid.UUID) ([]ListActivePeersForNodeRow, error) {
	rows, err := q.db.Query(ctx, listActivePeersForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePeersForNodeRow{}
	for rows.Next() {
		var i ListActivePeersForNodeRow
		if err := rows.Scan(&i.PublicKey, &i.AssignedIp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByOrg = `-- name: ListDevicesByOrg :many
SELECT d.id, d.org_id, d.user_id, d.node_id, d.name, d.platform, d.public_key, d.assigned_ip, d.status, d.created_at, d.updated_at, d.revoked_at, d.deleted_at, d.full_tunnel, d.approved_by, ds.last_handshake_at, ds.rx_bytes, ds.tx_bytes
FROM devices d
LEFT JOIN device_status ds ON ds.device_id = d.id
WHERE d.org_id = $1 AND d.deleted_at IS NULL
ORDER BY d.created_at
`

type ListDevicesByOrgRow struct {
	Device          Device             `json:"device"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         *int64             `json:"rx_bytes"`
	TxBytes         *int64             `json:"tx_bytes"`
}

func (q *Queries) ListDevicesByOrg(ctx context.Context, orgID uuid.UUID) ([]ListDevicesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesByOrgRow{}
	for rows.Next() {
		var i ListDevicesByOrgRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.OrgID,
			&i.Device.UserID,
			&i.Device.NodeID,
			&i.Device.Name,
			&i.Device.Platform,
			&i.Device.PublicKey,
			&i.Device.AssignedIp,
			&i.Device.Status,
			&i.Device.CreatedAt,
			&i.Device.UpdatedAt,
			&i.Device.RevokedAt,
			&i.Device.DeletedAt,
			&i.Device.FullTunnel,
			&i.Device.ApprovedBy,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT d.id, d.org_id, d.user_id, d.node_id, d.name, d.platform, d.public_key, d.assigned_ip, d.status, d.created_at, d.updated_at, d.revoked_at, d.deleted_at, d.full_tunnel, d.approved_by, ds.last_handshake_at, ds.rx_bytes, ds.tx_bytes
FROM devices d
LEFT JOIN device_status ds ON ds.device_id = d.id
WHERE d.org_id = $1 AND d.user_id = $2 AND d.deleted_at IS NULL
ORDER BY d.created_at
`

type ListDevicesByUserParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListDevicesByUserRow struct {
	Device          Device             `json:"device"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         *int64             `json:"rx_bytes"`
	TxBytes         *int64             `json:"tx_bytes"`
}

func (q *Queries) ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]ListDevicesByUserRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesByUserRow{}
	for rows.Next() {
		var i ListDevicesByUserRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.OrgID,
			&i.Device.UserID,
			&i.Device.NodeID,
			&i.Device.Name,
			&i.Device.Platform,
			&i.Device.PublicKey,
			&i.Device.AssignedIp,
			&i.Device.Status,
			&i.Device.CreatedAt,
			&i.Device.UpdatedAt,
			&i.Device.RevokedAt,
			&i.Device.DeletedAt,
			&i.Device.FullTunnel,
			&i.Device.ApprovedBy,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeIDsForUserActiveDevices = `-- name: ListNodeIDsForUserActiveDevices :many
SELECT DISTINCT node_id FROM devices
WHERE user_id = $1 AND status = 'active' AND deleted_at IS NULL
`

// lint:cross-org — keyed by user_id; used to find which nodes to push after a
// user's peers change (create/revoke/deactivate). Not org-scoped: a user's
// devices may span orgs and all affected nodes must be nudged to reconcile.
func (q *Queries) ListNodeIDsForUserActiveDevices(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listNodeIDsForUserActiveDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var node_id uuid.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDevicesByOrg = `-- name: ListPendingDevicesByOrg :many
SELECT d.id, d.org_id, d.user_id, d.node_id, d.name, d.platform, d.public_key, d.assigned_ip, d.status, d.created_at, d.updated_at, d.revoked_at, d.deleted_at, d.full_tunnel, d.approved_by, ds.last_handshake_at, ds.rx_bytes, ds.tx_bytes
FROM devices d
LEFT JOIN device_status ds ON ds.device_id = d.id
WHERE d.org_id = $1 AND d.status = 'pending' AND d.deleted_at IS NULL
ORDER BY d.created_at
`

type ListPendingDevicesByOrgRow struct {
	Device          Device             `json:"device"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         *int64             `json:"rx_bytes"`
	TxBytes         *int64             `json:"tx_bytes"`
}

// The approval queue (S7.3): devices awaiting admin approval, oldest first.
func (q *Queries) ListPendingDevicesByOrg(ctx context.Context, orgID uuid.UUID) ([]ListPendingDevicesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listPendingDevicesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDevicesByOrgRow{}
	for rows.Next() {
		var i ListPendingDevicesByOrgRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.OrgID,
			&i.Device.UserID,
			&i.Device.NodeID,
			&i.Device.Name,
			&i.Device.Platform,
			&i.Device.PublicKey,
			&i.Device.AssignedIp,
			&i.Device.Status,
			&i.Device.CreatedAt,
			&i.Device.UpdatedAt,
			&i.Device.RevokedAt,
			&i.Device.DeletedAt,
			&i.Device.FullTunnel,
			&i.Device.ApprovedBy,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceKey = `-- name: LockDeviceKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// lint:cross-org — a transaction-scoped advisory lock on an arbitrary key (a
// user id or org id, passed as text). Create takes BOTH (in sorted order, so no
// deadlock) to make the per-user cap check AND the org-wide IP allocation atomic
// against concurrent creates.
//
// TWO CLIENTS, both load-bearing: (1) device allocation (per-org mutual
// exclusion); (2) CIDR resize (S4.5b) — ResizePool takes the org key so its
// orphan check can't race a concurrent allocation during the resize window. A
// future S3.5 refactor that rescopes/weakens this lock (per-device keys, etc.)
// MUST keep resize and allocation contending on the SAME per-org key, or it
// silently reopens that race — see TestResizeAllocationRace (the red-without-lock
// guard). Resize takes only the org key; allocation takes {owner,org} sorted;
// resize never waits on the owner key, so no inversion/deadlock.
func (q *Queries) LockDeviceKey(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockDeviceKey, dollar_1)
	return err
}

const rejectDevice = `-- name: RejectDevice :one
UPDATE devices
SET status = 'revoked', revoked_at = now(), assigned_ip = NULL
WHERE id = $1 AND org_id = $2 AND status = 'pending' AND deleted_at IS NULL
RETURNING node_id
`

type RejectDeviceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// S7.3: pending -> revoked, FREEING the held pool IP (assigned_ip=NULL) so it returns to
// the pool for reuse (D1b — the same release RevokeDevice does). Only a PENDING device
// can be rejected. Returns node_id for the (own-node) push.
func (q *Queries) RejectDevice(ctx context.Context, arg RejectDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rejectDevice, arg.ID, arg.OrgID)
	var node_id uuid.UUID
	err := row.Scan(&node_id)
	return node_id, err
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices
SET status = 'revoked', revoked_at = now(), assigned_ip = NULL
WHERE id = $1 AND org_id = $2 AND status IN ('active', 'pending') AND deleted_at IS NULL
RETURNING node_id
`

type RevokeDeviceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Terminal revocation of an active OR pending device (S7.3 finding #3: an owner may CANCEL
// their own pending enrollment via this path). Full-sweep: clears assigned_ip (frees the
// pool address). Returns the gateway node_id for the push. The caller reads the PRIOR status
// (via GetDevice, in-tx) to audit distinctly (pending -> device.cancelled, active ->
// device.revoked). pgx.ErrNoRows means the device was neither active nor pending.
func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeDevice, arg.ID, arg.OrgID)
	var node_id uuid.UUID
	err := row.Scan(&node_id)
	return node_id, err
}

const revokeDevicesForNode = `-- name: RevokeDevicesForNode :execrows
UPDATE devices
SET status = 'revoked', revoked_at = now(), assigned_ip = NULL
WHERE node_id = $1 AND status IN ('active', 'pending') AND deleted_at IS NULL
`

// lint:cross-org — keyed by node_id; when a node is revoked its peers can no longer reach a
// gateway, so they are revoked too (no dangling devices). Sweeps ACTIVE + PENDING (S7.3
// finding #2: a pending device on a revoked node would otherwise leak its /32 forever and
// linger in the approval queue pointing at a dead gateway) and frees the address (full sweep).
func (q *Queries) RevokeDevicesForNode(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDevicesForNode, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrgDeviceApproval = `-- name: SetOrgDeviceApproval :one
UPDATE organizations SET device_approval = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, created_at, updated_at, deleted_at, max_devices_per_user, pool_cidr, zero_trust_mode, device_approval
`

type SetOrgDeviceApprovalParams struct {
	ID             uuid.UUID `json:"id"`
	DeviceApproval string    `json:"device_approval"`
}

// S7.3: flip the org device-approval gate. Enterprise-gated at the HTTP layer; the open
// build can never set it 'on', so enrollment there stays immediately-active.
func (q *Queries) SetOrgDeviceApproval(ctx context.Context, arg SetOrgDeviceApprovalParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrgDeviceApproval, arg.ID, arg.DeviceApproval)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaxDevicesPerUser,
		&i.PoolCidr,
		&i.ZeroTrustMode,
		&i.DeviceApproval,
	)
	return i, err
}
