// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveDevicesForUser = `-- name: CountActiveDevicesForUser :one
SELECT count(*) FROM devices
WHERE org_id = $1 AND user_id = $2 AND status = 'active' AND deleted_at IS NULL
`

type CountActiveDevicesForUserParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CountActiveDevicesForUser(ctx context.Context, arg CountActiveDevicesForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDevicesForUser, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (org_id, user_id, node_id, name, platform, public_key, assigned_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, user_id, node_id, name, platform, public_key, assigned_ip, status, created_at, updated_at, revoked_at, deleted_at
`

type CreateDeviceParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	UserID     uuid.UUID `json:"user_id"`
	NodeID     uuid.UUID `json:"node_id"`
	Name       string    `json:"name"`
	Platform   string    `json:"platform"`
	PublicKey  string    `json:"public_key"`
	AssignedIp *string   `json:"assigned_ip"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.OrgID,
		arg.UserID,
		arg.NodeID,
		arg.Name,
		arg.Platform,
		arg.PublicKey,
		arg.AssignedIp,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.NodeID,
		&i.Name,
		&i.Platform,
		&i.PublicKey,
		&i.AssignedIp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDeviceStatus = `-- name: DeleteDeviceStatus :exec
DELETE FROM device_status WHERE device_id = $1
`

// lint:cross-org — keyed by device_id (the caller already authorized the device
// via its org). Clears a device's live status (on revoke) so a revoked device
// never reports stale online/handshake via the API.
func (q *Queries) DeleteDeviceStatus(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceStatus, deviceID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, org_id, user_id, node_id, name, platform, public_key, assigned_ip, status, created_at, updated_at, revoked_at, deleted_at FROM devices
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetDeviceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.OrgID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.NodeID,
		&i.Name,
		&i.Platform,
		&i.PublicKey,
		&i.AssignedIp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgNode = `-- name: GetOrgNode :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint FROM nodes
WHERE id = $1 AND org_id = $2 AND status = 'active'
`

type GetOrgNodeParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Verifies a node belongs to the org (id+org scoped) before a device attaches to it.
func (q *Queries) GetOrgNode(ctx context.Context, arg GetOrgNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, getOrgNode, arg.ID, arg.OrgID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
	)
	return i, err
}

const listActiveDeviceAllocations = `-- name: ListActiveDeviceAllocations :many
SELECT id, name, assigned_ip FROM devices
WHERE org_id = $1 AND assigned_ip IS NOT NULL AND status = 'active' AND deleted_at IS NULL
ORDER BY assigned_ip
`

type ListActiveDeviceAllocationsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	AssignedIp *string   `json:"assigned_ip"`
}

// Live allocations WITH the owning device (id, name) — the SINGLE source for the
// resize orphan check AND the 409 orphan objects, so the check and the build
// can't drift (one read under the org lock). Filters MUST stay identical to
// ListAssignedIPsForOrg (active, non-deleted, assigned_ip set).
func (q *Queries) ListActiveDeviceAllocations(ctx context.Context, orgID uuid.UUID) ([]ListActiveDeviceAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceAllocations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDeviceAllocationsRow{}
	for rows.Next() {
		var i ListActiveDeviceAllocationsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AssignedIp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePeersForNode = `-- name: ListActivePeersForNode :many
SELECT d.public_key, d.assigned_ip
FROM devices d
JOIN users u ON u.id = d.user_id
WHERE d.node_id = $1
  AND d.status = 'active' AND d.deleted_at IS NULL
  AND u.status = 'active' AND u.deleted_at IS NULL
ORDER BY d.created_at
`

type ListActivePeersForNodeRow struct {
	PublicKey  string  `json:"public_key"`
	AssignedIp *string `json:"assigned_ip"`
}

// lint:cross-org — keyed by node_id after mTLS cert authorization (the agent
// fetches the peers for its own node). A peer is present only while BOTH the
// device is active AND its owning user is active — so deactivating a user drops
// their peers from every node's desired state (and reactivation restores them).
func (q *Queries) ListActivePeersForNode(ctx context.Context, nodeID uuid.UUID) ([]ListActivePeersForNodeRow, error) {
	rows, err := q.db.Query(ctx, listActivePeersForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePeersForNodeRow{}
	for rows.Next() {
		var i ListActivePeersForNodeRow
		if err := rows.Scan(&i.PublicKey, &i.AssignedIp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedIPsForOrg = `-- name: ListAssignedIPsForOrg :many
SELECT assigned_ip FROM devices
WHERE org_id = $1 AND assigned_ip IS NOT NULL AND status = 'active' AND deleted_at IS NULL
`

// The org's live tunnel allocations (flat pool, across all nodes). Read under the
// org advisory lock during Create so the lowest-free choice can't be raced.
func (q *Queries) ListAssignedIPsForOrg(ctx context.Context, orgID uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listAssignedIPsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var assigned_ip *string
		if err := rows.Scan(&assigned_ip); err != nil {
			return nil, err
		}
		items = append(items, assigned_ip)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByOrg = `-- name: ListDevicesByOrg :many
SELECT d.id, d.org_id, d.user_id, d.node_id, d.name, d.platform, d.public_key, d.assigned_ip, d.status, d.created_at, d.updated_at, d.revoked_at, d.deleted_at, ds.last_handshake_at, ds.rx_bytes, ds.tx_bytes
FROM devices d
LEFT JOIN device_status ds ON ds.device_id = d.id
WHERE d.org_id = $1 AND d.deleted_at IS NULL
ORDER BY d.created_at
`

type ListDevicesByOrgRow struct {
	Device          Device             `json:"device"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         *int64             `json:"rx_bytes"`
	TxBytes         *int64             `json:"tx_bytes"`
}

func (q *Queries) ListDevicesByOrg(ctx context.Context, orgID uuid.UUID) ([]ListDevicesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesByOrgRow{}
	for rows.Next() {
		var i ListDevicesByOrgRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.OrgID,
			&i.Device.UserID,
			&i.Device.NodeID,
			&i.Device.Name,
			&i.Device.Platform,
			&i.Device.PublicKey,
			&i.Device.AssignedIp,
			&i.Device.Status,
			&i.Device.CreatedAt,
			&i.Device.UpdatedAt,
			&i.Device.RevokedAt,
			&i.Device.DeletedAt,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT d.id, d.org_id, d.user_id, d.node_id, d.name, d.platform, d.public_key, d.assigned_ip, d.status, d.created_at, d.updated_at, d.revoked_at, d.deleted_at, ds.last_handshake_at, ds.rx_bytes, ds.tx_bytes
FROM devices d
LEFT JOIN device_status ds ON ds.device_id = d.id
WHERE d.org_id = $1 AND d.user_id = $2 AND d.deleted_at IS NULL
ORDER BY d.created_at
`

type ListDevicesByUserParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListDevicesByUserRow struct {
	Device          Device             `json:"device"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RxBytes         *int64             `json:"rx_bytes"`
	TxBytes         *int64             `json:"tx_bytes"`
}

func (q *Queries) ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]ListDevicesByUserRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesByUserRow{}
	for rows.Next() {
		var i ListDevicesByUserRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.OrgID,
			&i.Device.UserID,
			&i.Device.NodeID,
			&i.Device.Name,
			&i.Device.Platform,
			&i.Device.PublicKey,
			&i.Device.AssignedIp,
			&i.Device.Status,
			&i.Device.CreatedAt,
			&i.Device.UpdatedAt,
			&i.Device.RevokedAt,
			&i.Device.DeletedAt,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeIDsForUserActiveDevices = `-- name: ListNodeIDsForUserActiveDevices :many
SELECT DISTINCT node_id FROM devices
WHERE user_id = $1 AND status = 'active' AND deleted_at IS NULL
`

// lint:cross-org — keyed by user_id; used to find which nodes to push after a
// user's peers change (create/revoke/deactivate). Not org-scoped: a user's
// devices may span orgs and all affected nodes must be nudged to reconcile.
func (q *Queries) ListNodeIDsForUserActiveDevices(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listNodeIDsForUserActiveDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var node_id uuid.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceKey = `-- name: LockDeviceKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// lint:cross-org — a transaction-scoped advisory lock on an arbitrary key (a
// user id or org id, passed as text). Create takes BOTH (in sorted order, so no
// deadlock) to make the per-user cap check AND the org-wide IP allocation atomic
// against concurrent creates.
//
// TWO CLIENTS, both load-bearing: (1) device allocation (per-org mutual
// exclusion); (2) CIDR resize (S4.5b) — ResizePool takes the org key so its
// orphan check can't race a concurrent allocation during the resize window. A
// future S3.5 refactor that rescopes/weakens this lock (per-device keys, etc.)
// MUST keep resize and allocation contending on the SAME per-org key, or it
// silently reopens that race — see TestResizeAllocationRace (the red-without-lock
// guard). Resize takes only the org key; allocation takes {owner,org} sorted;
// resize never waits on the owner key, so no inversion/deadlock.
func (q *Queries) LockDeviceKey(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockDeviceKey, dollar_1)
	return err
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices
SET status = 'revoked', revoked_at = now(), assigned_ip = NULL
WHERE id = $1 AND org_id = $2 AND status = 'active' AND deleted_at IS NULL
RETURNING node_id
`

type RevokeDeviceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Returns the gateway node_id (for the push) so the caller needs no extra read;
// pgx.ErrNoRows means the device was not active (already revoked / wrong org).
// Clears assigned_ip to release the address explicitly (rather than relying on
// every reader to also filter status='active').
func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeDevice, arg.ID, arg.OrgID)
	var node_id uuid.UUID
	err := row.Scan(&node_id)
	return node_id, err
}

const revokeDevicesForNode = `-- name: RevokeDevicesForNode :execrows
UPDATE devices
SET status = 'revoked', revoked_at = now()
WHERE node_id = $1 AND status = 'active' AND deleted_at IS NULL
`

// lint:cross-org — keyed by node_id; when a node is revoked its peers can no
// longer reach a gateway, so they are revoked too (no dangling active devices).
func (q *Queries) RevokeDevicesForNode(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDevicesForNode, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
