// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: k8s.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const createK8sCluster = `-- name: CreateK8sCluster :one

INSERT INTO k8s_clusters (org_id, site_id, name, vip_range)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, site_id, name, vip_range, created_at, updated_at
`

type CreateK8sClusterParams struct {
	OrgID    uuid.UUID    `json:"org_id"`
	SiteID   uuid.UUID    `json:"site_id"`
	Name     string       `json:"name"`
	VipRange netip.Prefix `json:"vip_range"`
}

// S10.3: Kubernetes cluster + exposed-Service queries. Org-scoped (tenant isolation).
func (q *Queries) CreateK8sCluster(ctx context.Context, arg CreateK8sClusterParams) (K8sCluster, error) {
	row := q.db.QueryRow(ctx, createK8sCluster,
		arg.OrgID,
		arg.SiteID,
		arg.Name,
		arg.VipRange,
	)
	var i K8sCluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.VipRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createK8sService = `-- name: CreateK8sService :one
INSERT INTO k8s_services (org_id, cluster_id, name, namespace, protocol, port_low, port_high, vip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, cluster_id, name, namespace, protocol, port_low, port_high, vip, created_at, updated_at, deleted_at
`

type CreateK8sServiceParams struct {
	OrgID     uuid.UUID  `json:"org_id"`
	ClusterID uuid.UUID  `json:"cluster_id"`
	Name      string     `json:"name"`
	Namespace string     `json:"namespace"`
	Protocol  string     `json:"protocol"`
	PortLow   *int32     `json:"port_low"`
	PortHigh  *int32     `json:"port_high"`
	Vip       netip.Addr `json:"vip"`
}

func (q *Queries) CreateK8sService(ctx context.Context, arg CreateK8sServiceParams) (K8sService, error) {
	row := q.db.QueryRow(ctx, createK8sService,
		arg.OrgID,
		arg.ClusterID,
		arg.Name,
		arg.Namespace,
		arg.Protocol,
		arg.PortLow,
		arg.PortHigh,
		arg.Vip,
	)
	var i K8sService
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClusterID,
		&i.Name,
		&i.Namespace,
		&i.Protocol,
		&i.PortLow,
		&i.PortHigh,
		&i.Vip,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteK8sCluster = `-- name: DeleteK8sCluster :exec
DELETE FROM k8s_clusters WHERE org_id = $1 AND id = $2
`

type DeleteK8sClusterParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) DeleteK8sCluster(ctx context.Context, arg DeleteK8sClusterParams) error {
	_, err := q.db.Exec(ctx, deleteK8sCluster, arg.OrgID, arg.ID)
	return err
}

const getK8sCluster = `-- name: GetK8sCluster :one
SELECT id, org_id, site_id, name, vip_range, created_at, updated_at FROM k8s_clusters WHERE org_id = $1 AND id = $2
`

type GetK8sClusterParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetK8sCluster(ctx context.Context, arg GetK8sClusterParams) (K8sCluster, error) {
	row := q.db.QueryRow(ctx, getK8sCluster, arg.OrgID, arg.ID)
	var i K8sCluster
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.VipRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getK8sService = `-- name: GetK8sService :one
SELECT id, org_id, cluster_id, name, namespace, protocol, port_low, port_high, vip, created_at, updated_at, deleted_at FROM k8s_services WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetK8sServiceParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) GetK8sService(ctx context.Context, arg GetK8sServiceParams) (K8sService, error) {
	row := q.db.QueryRow(ctx, getK8sService, arg.OrgID, arg.ID)
	var i K8sService
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClusterID,
		&i.Name,
		&i.Namespace,
		&i.Protocol,
		&i.PortLow,
		&i.PortHigh,
		&i.Vip,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveK8sServicesForOrg = `-- name: ListActiveK8sServicesForOrg :many
SELECT s.id, s.cluster_id, s.name, s.namespace, s.protocol, s.port_low, s.port_high,
       host(s.vip) AS vip, c.site_id, host(c.vip_range) AS vip_range
FROM k8s_services s
JOIN k8s_clusters c ON c.id = s.cluster_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL
ORDER BY s.id
`

type ListActiveK8sServicesForOrgRow struct {
	ID        uuid.UUID `json:"id"`
	ClusterID uuid.UUID `json:"cluster_id"`
	Name      string    `json:"name"`
	Namespace string    `json:"namespace"`
	Protocol  string    `json:"protocol"`
	PortLow   *int32    `json:"port_low"`
	PortHigh  *int32    `json:"port_high"`
	Vip       string    `json:"vip"`
	SiteID    uuid.UUID `json:"site_id"`
	VipRange  string    `json:"vip_range"`
}

// ListActiveK8sServicesForOrg is the compiler's resolution source: id -> current VIP (+ proto/ports), LIVE
// only. A soft-deleted Service is absent, so a grant referencing it compiles to nothing (honest, not silent).
func (q *Queries) ListActiveK8sServicesForOrg(ctx context.Context, orgID uuid.UUID) ([]ListActiveK8sServicesForOrgRow, error) {
	rows, err := q.db.Query(ctx, listActiveK8sServicesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveK8sServicesForOrgRow{}
	for rows.Next() {
		var i ListActiveK8sServicesForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Name,
			&i.Namespace,
			&i.Protocol,
			&i.PortLow,
			&i.PortHigh,
			&i.Vip,
			&i.SiteID,
			&i.VipRange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listK8sClustersForOrg = `-- name: ListK8sClustersForOrg :many
SELECT id, org_id, site_id, name, vip_range, created_at, updated_at FROM k8s_clusters WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListK8sClustersForOrg(ctx context.Context, orgID uuid.UUID) ([]K8sCluster, error) {
	rows, err := q.db.Query(ctx, listK8sClustersForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []K8sCluster{}
	for rows.Next() {
		var i K8sCluster
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.Name,
			&i.VipRange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedVIPsInCluster = `-- name: ListUsedVIPsInCluster :many
SELECT host(vip) AS vip FROM k8s_services WHERE cluster_id = $1 AND deleted_at IS NULL
`

// ListUsedVIPsInCluster returns the LIVE VIPs in a cluster (the used-set ipalloc allocates around).
func (q *Queries) ListUsedVIPsInCluster(ctx context.Context, clusterID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsedVIPsInCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var vip string
		if err := rows.Scan(&vip); err != nil {
			return nil, err
		}
		items = append(items, vip)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVIPRangesForOrg = `-- name: ListVIPRangesForOrg :many
SELECT vip_range::text AS vip_range FROM k8s_clusters WHERE org_id = $1
`

// ListVIPRangesForOrg feeds the subnetguard collector: EVERY disjointness check (cluster-VIP creation,
// pool resize, site-subnet approval) must include the org's VIP ranges so disjointness stays bidirectional
// (the validator-input-filtering law). Returns the raw cidr text.
func (q *Queries) ListVIPRangesForOrg(ctx context.Context, orgID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listVIPRangesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var vip_range string
		if err := rows.Scan(&vip_range); err != nil {
			return nil, err
		}
		items = append(items, vip_range)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteK8sService = `-- name: SoftDeleteK8sService :exec
UPDATE k8s_services SET deleted_at = now() WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteK8sServiceParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteK8sService(ctx context.Context, arg SoftDeleteK8sServiceParams) error {
	_, err := q.db.Exec(ctx, softDeleteK8sService, arg.OrgID, arg.ID)
	return err
}
