// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machine_credentials.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignMachineCredentialOwner = `-- name: AssignMachineCredentialOwner :execrows
UPDATE machine_credentials mc
SET user_id = $3
WHERE mc.id = $1
  AND mc.org_id = $2
  AND mc.revoked_at IS NULL
  -- ⚠ MEMBERSHIP IS RELATIONAL — ` + "`" + `users` + "`" + ` has NO org_id (measured, not assumed; the first draft of this
  -- statement joined a column that does not exist and would have matched nothing). Org scoping goes through
  -- ` + "`" + `memberships` + "`" + `, and the user must still be live.
  -- ⛔ AND VERIFIED (D21). Enforced IN THE STATEMENT, not only in the handler's pre-check: a client-side
  -- filter is a presentation decision, and the pre-check can be raced by a verification being revoked
  -- between read and write. This is the authorization decision, so it lives where the write happens.
  AND EXISTS (
      SELECT 1 FROM memberships m
      JOIN users u ON u.id = m.user_id
      WHERE m.user_id = $3 AND m.org_id = $2
        AND u.deleted_at IS NULL AND u.status = 'active'
        AND u.email_verified_at IS NOT NULL
  )
`

type AssignMachineCredentialOwnerParams struct {
	ID     uuid.UUID   `json:"id"`
	OrgID  uuid.UUID   `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// S15.1 (D14/D19 step 2) — an admin NAMES the owner. There is no created_by on this table, so the minting
// user is not recoverable from the row: the admin is CHOOSING, not confirming, and nothing here guesses.
//
// ⛔ THE OWNER MUST BE IN THE CREDENTIAL'S ORG, ENFORCED IN THE STATEMENT. A cross-org owner would attribute a
// machine principal to someone who cannot see it. The EXISTS is org-scoped both ways — credential and user —
// so a mismatched pair updates zero rows rather than succeeding quietly.
func (q *Queries) AssignMachineCredentialOwner(ctx context.Context, arg AssignMachineCredentialOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignMachineCredentialOwner, arg.ID, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMachineCredential = `-- name: CreateMachineCredential :one

INSERT INTO machine_credentials (org_id, name, role, token_hash, fingerprint)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, role, token_hash, fingerprint, created_at, last_used_at, revoked_at, user_id
`

type CreateMachineCredentialParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Role        string    `json:"role"`
	TokenHash   []byte    `json:"token_hash"`
	Fingerprint string    `json:"fingerprint"`
}

// Machine credentials (S10.2): an org-scoped, NON-USER principal for the GitOps operator. Mirror of the
// cli_credentials pattern — sha256 hash storage, fingerprint-only display, revoke-severs-on-next-request.
// The raw token NEVER reaches SQL. Revoke is org-scoped (a caller can only revoke its own org's creds).
func (q *Queries) CreateMachineCredential(ctx context.Context, arg CreateMachineCredentialParams) (MachineCredential, error) {
	row := q.db.QueryRow(ctx, createMachineCredential,
		arg.OrgID,
		arg.Name,
		arg.Role,
		arg.TokenHash,
		arg.Fingerprint,
	)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Role,
		&i.TokenHash,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getMachineCredentialByHash = `-- name: GetMachineCredentialByHash :one
SELECT id, org_id, name, role, token_hash, fingerprint, created_at, last_used_at, revoked_at, user_id FROM machine_credentials WHERE token_hash = $1
`

// lint:cross-org — an auth lookup by the secret HASH; the row resolves the org (the hash IS the credential).
// Returns the row regardless of revoked state — the auth path applies the NO-ORACLE check (revoked /
// unknown are indistinguishable at the wire), exactly like the CLI credential path.
func (q *Queries) GetMachineCredentialByHash(ctx context.Context, tokenHash []byte) (MachineCredential, error) {
	row := q.db.QueryRow(ctx, getMachineCredentialByHash, tokenHash)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Role,
		&i.TokenHash,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getMachineOwnerStanding = `-- name: GetMachineOwnerStanding :one
SELECT
  (u.status = 'active')::boolean AS active,
  EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.org_id = $2)::boolean AS in_org
FROM users u
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetMachineOwnerStandingParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

type GetMachineOwnerStandingRow struct {
	Active bool `json:"active"`
	InOrg  bool `json:"in_org"`
}

// ⛔ D23: IS THE OWNER OF THIS CREDENTIAL STILL ACCOUNTABLE FOR IT?
//
// D14 bound machine credentials to a human so accountability exists. The binding was checked at REST (the
// column is set) and never at USE — so a credential whose owner was deactivated, soft-deleted, or removed
// from the organization kept authenticating indefinitely. That is the ruling with its point removed: the
// owner stops being accountable and nothing stops the credential.
//
// ⚠ ONE QUERY, THREE FACTS, because they are one question. Two round trips would invite a caller to check
// the cheap one and skip the other.
//   - no row at all      => the owner is soft-deleted (users are read `deleted_at IS NULL` everywhere)
//   - active = false     => deactivated, which SessionAuth and the CLI bearer already refuse for humans
//   - in_org = false     => removed from the organization this credential acts in
//
// ⛔ EMAIL VERIFICATION IS DELIBERATELY NOT HERE. A machine principal is EXEMPT from the human email gate
// by construction (authorize() skips it for IsMachine), the bootstrap administrator is pre-verified by
// design, and an invited operator can be mid-flow — refusing on it would contradict a ruling rather than
// enforce one.
// lint:cross-org — reads a membership for the credential's OWN org, passed in by the caller.
func (q *Queries) GetMachineOwnerStanding(ctx context.Context, arg GetMachineOwnerStandingParams) (GetMachineOwnerStandingRow, error) {
	row := q.db.QueryRow(ctx, getMachineOwnerStanding, arg.ID, arg.OrgID)
	var i GetMachineOwnerStandingRow
	err := row.Scan(&i.Active, &i.InOrg)
	return i, err
}

const getOrgMemberVerification = `-- name: GetOrgMemberVerification :one
SELECT (u.email_verified_at IS NOT NULL)::boolean AS email_verified
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND m.user_id = $2
  AND u.deleted_at IS NULL AND u.status = 'active'
`

type GetOrgMemberVerificationParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

// S15.1 / D21 — is this user eligible to be named as an accountable owner?
//
// ⛔ RULED NO FOR UNVERIFIED ACCOUNTS. Ownership is an ACCOUNTABILITY CLAIM, and an account that cannot
// perform org mutations (requireVerifiedUser gates those) cannot be held accountable for what a credential
// does. Nameable-but-unable-to-act is a contradiction the screen would render as fact.
//
// ⚠ THIS EXISTS FOR THE MESSAGE, NOT FOR THE TRUTH. The refusal is enforced in the UPDATE statement itself,
// which cannot be raced; this read only lets the handler say WHICH precondition failed instead of returning
// an undifferentiated not-found. No oracle is created: the caller holds machine:manage and can already read
// every member's email_verified from the roster.
//
// No row = not a live member of this org (already the AssignOwner failure mode).
func (q *Queries) GetOrgMemberVerification(ctx context.Context, arg GetOrgMemberVerificationParams) (bool, error) {
	row := q.db.QueryRow(ctx, getOrgMemberVerification, arg.OrgID, arg.UserID)
	var email_verified bool
	err := row.Scan(&email_verified)
	return email_verified, err
}

const listMachineCredentialsForOrg = `-- name: ListMachineCredentialsForOrg :many
SELECT mc.id, mc.org_id, mc.name, mc.role, mc.token_hash, mc.fingerprint, mc.created_at, mc.last_used_at, mc.revoked_at, mc.user_id, u.email AS owner_email
FROM machine_credentials mc
LEFT JOIN users u ON u.id = mc.user_id
WHERE mc.org_id = $1 AND mc.revoked_at IS NULL
ORDER BY mc.created_at DESC
`

type ListMachineCredentialsForOrgRow struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	TokenHash   []byte             `json:"token_hash"`
	Fingerprint string             `json:"fingerprint"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	UserID      pgtype.UUID        `json:"user_id"`
	OwnerEmail  *string            `json:"owner_email"`
}

// ⛔ owner_email IS RESOLVED HERE, FROM `users` AND NOT FROM `memberships` (S15.1, D22 ruled).
//
// The field was on the DTO, documented as "resolved from owner_user_id for display", and NEVER POPULATED —
// the web resolved it from the member roster it already fetches. That is correct until the owner LEAVES THE
// ORG, at which point the roster cannot name them and the accountability screen goes blank on precisely the
// row accountability exists for.
//
// ⚠ LEFT JOIN ON `users`, WHICH SURVIVES BOTH LOSSES THE ROSTER DOES NOT: membership deletion (nothing pins
// it) and deactivation. The FK is ON DELETE RESTRICT, so an assigned credential cannot outlive its user row —
// the recorded identity is always recoverable, and the LEFT JOIN is for the NULL owner, not for a missing user.
// lint:allow-deleted — DELIBERATE, AND IT IS THE RULING (D22), NOT A BYPASS.
// The lint's default is right for every query that ACTS on a user. This one does not act; it RESOLVES A
// RECORDED IDENTITY for display. Filtering `u.deleted_at IS NULL` here would blank the owner of a credential
// whose owner was soft-deleted — the exact failure D22 was ruled to end, arrived at from a different
// direction: the roster could not name a departed member, and `deleted_at` scoping cannot name a deleted one.
// ⚠ A screen whose purpose is accountability must not lose the name at the moment accountability matters.
func (q *Queries) ListMachineCredentialsForOrg(ctx context.Context, orgID uuid.UUID) ([]ListMachineCredentialsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listMachineCredentialsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMachineCredentialsForOrgRow{}
	for rows.Next() {
		var i ListMachineCredentialsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Role,
			&i.TokenHash,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.UserID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMachineCredential = `-- name: RevokeMachineCredential :execrows
UPDATE machine_credentials SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeMachineCredentialParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Org-scoped + idempotent (already-revoked returns 0 rows). Revocation severs on the very next request
// (the auth path re-reads the row every time — no session cache).
func (q *Queries) RevokeMachineCredential(ctx context.Context, arg RevokeMachineCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMachineCredential, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMachineCredentialUsed = `-- name: TouchMachineCredentialUsed :exec
UPDATE machine_credentials SET last_used_at = now() WHERE id = $1
`

// lint:cross-org — best-effort telemetry keyed by the credential id resolved from the hash lookup above.
func (q *Queries) TouchMachineCredentialUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMachineCredentialUsed, id)
	return err
}
