// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machine_credentials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignMachineCredentialOwner = `-- name: AssignMachineCredentialOwner :execrows
UPDATE machine_credentials mc
SET user_id = $3
WHERE mc.id = $1
  AND mc.org_id = $2
  AND mc.revoked_at IS NULL
  -- ⚠ MEMBERSHIP IS RELATIONAL — ` + "`" + `users` + "`" + ` has NO org_id (measured, not assumed; the first draft of this
  -- statement joined a column that does not exist and would have matched nothing). Org scoping goes through
  -- ` + "`" + `memberships` + "`" + `, and the user must still be live.
  AND EXISTS (
      SELECT 1 FROM memberships m
      JOIN users u ON u.id = m.user_id
      WHERE m.user_id = $3 AND m.org_id = $2
        AND u.deleted_at IS NULL AND u.status = 'active'
  )
`

type AssignMachineCredentialOwnerParams struct {
	ID     uuid.UUID   `json:"id"`
	OrgID  uuid.UUID   `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// S15.1 (D14/D19 step 2) — an admin NAMES the owner. There is no created_by on this table, so the minting
// user is not recoverable from the row: the admin is CHOOSING, not confirming, and nothing here guesses.
//
// ⛔ THE OWNER MUST BE IN THE CREDENTIAL'S ORG, ENFORCED IN THE STATEMENT. A cross-org owner would attribute a
// machine principal to someone who cannot see it. The EXISTS is org-scoped both ways — credential and user —
// so a mismatched pair updates zero rows rather than succeeding quietly.
func (q *Queries) AssignMachineCredentialOwner(ctx context.Context, arg AssignMachineCredentialOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignMachineCredentialOwner, arg.ID, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMachineCredential = `-- name: CreateMachineCredential :one

INSERT INTO machine_credentials (org_id, name, role, token_hash, fingerprint)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, role, token_hash, fingerprint, created_at, last_used_at, revoked_at, user_id
`

type CreateMachineCredentialParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Role        string    `json:"role"`
	TokenHash   []byte    `json:"token_hash"`
	Fingerprint string    `json:"fingerprint"`
}

// Machine credentials (S10.2): an org-scoped, NON-USER principal for the GitOps operator. Mirror of the
// cli_credentials pattern — sha256 hash storage, fingerprint-only display, revoke-severs-on-next-request.
// The raw token NEVER reaches SQL. Revoke is org-scoped (a caller can only revoke its own org's creds).
func (q *Queries) CreateMachineCredential(ctx context.Context, arg CreateMachineCredentialParams) (MachineCredential, error) {
	row := q.db.QueryRow(ctx, createMachineCredential,
		arg.OrgID,
		arg.Name,
		arg.Role,
		arg.TokenHash,
		arg.Fingerprint,
	)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Role,
		&i.TokenHash,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getMachineCredentialByHash = `-- name: GetMachineCredentialByHash :one
SELECT id, org_id, name, role, token_hash, fingerprint, created_at, last_used_at, revoked_at, user_id FROM machine_credentials WHERE token_hash = $1
`

// lint:cross-org — an auth lookup by the secret HASH; the row resolves the org (the hash IS the credential).
// Returns the row regardless of revoked state — the auth path applies the NO-ORACLE check (revoked /
// unknown are indistinguishable at the wire), exactly like the CLI credential path.
func (q *Queries) GetMachineCredentialByHash(ctx context.Context, tokenHash []byte) (MachineCredential, error) {
	row := q.db.QueryRow(ctx, getMachineCredentialByHash, tokenHash)
	var i MachineCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Role,
		&i.TokenHash,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const listMachineCredentialsForOrg = `-- name: ListMachineCredentialsForOrg :many
SELECT id, org_id, name, role, token_hash, fingerprint, created_at, last_used_at, revoked_at, user_id FROM machine_credentials
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMachineCredentialsForOrg(ctx context.Context, orgID uuid.UUID) ([]MachineCredential, error) {
	rows, err := q.db.Query(ctx, listMachineCredentialsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MachineCredential{}
	for rows.Next() {
		var i MachineCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Role,
			&i.TokenHash,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMachineCredential = `-- name: RevokeMachineCredential :execrows
UPDATE machine_credentials SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeMachineCredentialParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Org-scoped + idempotent (already-revoked returns 0 rows). Revocation severs on the very next request
// (the auth path re-reads the row every time — no session cache).
func (q *Queries) RevokeMachineCredential(ctx context.Context, arg RevokeMachineCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMachineCredential, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMachineCredentialUsed = `-- name: TouchMachineCredentialUsed :exec
UPDATE machine_credentials SET last_used_at = now() WHERE id = $1
`

// lint:cross-org — best-effort telemetry keyed by the credential id resolved from the hash lookup above.
func (q *Queries) TouchMachineCredentialUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMachineCredentialUsed, id)
	return err
}
