// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const changeMemberRole = `-- name: ChangeMemberRole :one
UPDATE memberships
SET role = $3
WHERE org_id = $1 AND user_id = $2
RETURNING id, org_id, user_id, role, created_at, updated_at
`

type ChangeMemberRoleParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) ChangeMemberRole(ctx context.Context, arg ChangeMemberRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, changeMemberRole, arg.OrgID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships
WHERE org_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, org_id, user_id, role, created_at, updated_at FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT id, org_id, user_id, role, created_at, updated_at FROM memberships
WHERE org_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembershipsByOrg(ctx context.Context, orgID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, org_id, user_id, role, created_at, updated_at FROM memberships
WHERE user_id = $1
ORDER BY created_at
`

// lint:cross-org — intentionally spans orgs: a user's memberships across all
// their organizations (used to resolve which orgs a principal belongs to).
func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE
    SET role = EXCLUDED.role
RETURNING id, org_id, user_id, role, created_at, updated_at
`

type UpsertMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

// Idempotent on (org_id, user_id).
func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, upsertMembership, arg.OrgID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
