// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeJoinToken = `-- name: ConsumeJoinToken :one
UPDATE node_join_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at
`

// lint:cross-org — the token itself is the credential; the org comes from the
// returned row. Single-use + expiring.
func (q *Queries) ConsumeJoinToken(ctx context.Context, tokenHash []byte) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, consumeJoinToken, tokenHash)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO node_join_tokens (org_id, node_name, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at
`

type CreateJoinTokenParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	NodeName  *string   `json:"node_name"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.OrgID,
		arg.NodeName,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (org_id, name, cert_serial, agent_version)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at
`

type CreateNodeParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	Name         string    `json:"name"`
	CertSerial   string    `json:"cert_serial"`
	AgentVersion string    `json:"agent_version"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.OrgID,
		arg.Name,
		arg.CertSerial,
		arg.AgentVersion,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByCertSerial = `-- name: GetNodeByCertSerial :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at FROM nodes
WHERE cert_serial = $1
`

// lint:cross-org — the mTLS client cert IS the identity; the org comes from the
// node row. Used to authorize every agent request.
func (q *Queries) GetNodeByCertSerial(ctx context.Context, certSerial string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByCertSerial, certSerial)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByOrgName = `-- name: GetNodeByOrgName :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at FROM nodes
WHERE org_id = $1 AND name = $2
`

type GetNodeByOrgNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetNodeByOrgName(ctx context.Context, arg GetNodeByOrgNameParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByOrgName, arg.OrgID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformSecret = `-- name: GetPlatformSecret :one
SELECT name, secret_sealed, public_pem, created_at, updated_at FROM platform_secrets WHERE name = $1
`

func (q *Queries) GetPlatformSecret(ctx context.Context, name string) (PlatformSecret, error) {
	row := q.db.QueryRow(ctx, getPlatformSecret, name)
	var i PlatformSecret
	err := row.Scan(
		&i.Name,
		&i.SecretSealed,
		&i.PublicPem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformSecret = `-- name: InsertPlatformSecret :exec
INSERT INTO platform_secrets (name, secret_sealed, public_pem)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO NOTHING
`

type InsertPlatformSecretParams struct {
	Name         string  `json:"name"`
	SecretSealed []byte  `json:"secret_sealed"`
	PublicPem    *string `json:"public_pem"`
}

// Create-if-absent; the caller reads-back on conflict. Never overwrites, so a
// concurrent boot can't clobber the CA (fail-loud-never-regenerate lives above).
func (q *Queries) InsertPlatformSecret(ctx context.Context, arg InsertPlatformSecretParams) error {
	_, err := q.db.Exec(ctx, insertPlatformSecret, arg.Name, arg.SecretSealed, arg.PublicPem)
	return err
}

const listNodes = `-- name: ListNodes :many
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at FROM nodes
WHERE org_id = $1
ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context, orgID uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CertSerial,
			&i.AgentVersion,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewNodeCert = `-- name: RenewNodeCert :exec
UPDATE nodes
SET cert_serial = $2, agent_version = $3, last_seen_at = now()
WHERE id = $1 AND status = 'active'
`

type RenewNodeCertParams struct {
	ID           uuid.UUID `json:"id"`
	CertSerial   string    `json:"cert_serial"`
	AgentVersion string    `json:"agent_version"`
}

// lint:cross-org — keyed by node id after the caller authorized via the current
// cert; renewal rotates the serial and stamps activity/version.
func (q *Queries) RenewNodeCert(ctx context.Context, arg RenewNodeCertParams) error {
	_, err := q.db.Exec(ctx, renewNodeCert, arg.ID, arg.CertSerial, arg.AgentVersion)
	return err
}

const revokeNode = `-- name: RevokeNode :exec
UPDATE nodes
SET status = 'revoked', revoked_at = now()
WHERE org_id = $1 AND id = $2
`

type RevokeNodeParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) RevokeNode(ctx context.Context, arg RevokeNodeParams) error {
	_, err := q.db.Exec(ctx, revokeNode, arg.OrgID, arg.ID)
	return err
}

const touchNodeSeen = `-- name: TouchNodeSeen :exec
UPDATE nodes
SET last_seen_at = now()
WHERE id = $1
`

// lint:cross-org — keyed by id after cert authorization.
func (q *Queries) TouchNodeSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchNodeSeen, id)
	return err
}
