// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearNodePolicyDesyncSince = `-- name: ClearNodePolicyDesyncSince :exec
UPDATE nodes SET policy_desync_since = NULL WHERE id = $1 AND org_id = $2 AND policy_desync_since IS NOT NULL
`

type ClearNodePolicyDesyncSinceParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// S7.4b (X-4): clear the desync stamp on RECONVERGENCE or non-enforcing (applied == pushed,
// or pushed == "" ). Convergence is a STATE predicate — revert-to-clear (admin reverts the
// pushed target back to the applied hash) legitimately clears. CP-only, single-writer, org-scoped.
func (q *Queries) ClearNodePolicyDesyncSince(ctx context.Context, arg ClearNodePolicyDesyncSinceParams) error {
	_, err := q.db.Exec(ctx, clearNodePolicyDesyncSince, arg.ID, arg.OrgID)
	return err
}

const consumeJoinToken = `-- name: ConsumeJoinToken :one
UPDATE node_join_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at
`

// lint:cross-org — the token itself is the credential; the org comes from the
// returned row. Single-use + expiring.
func (q *Queries) ConsumeJoinToken(ctx context.Context, tokenHash []byte) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, consumeJoinToken, tokenHash)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO node_join_tokens (org_id, node_name, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, node_name, token_hash, expires_at, consumed_at, consumed_node_id, created_at
`

type CreateJoinTokenParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	NodeName  *string   `json:"node_name"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (NodeJoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.OrgID,
		arg.NodeName,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i NodeJoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeName,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (org_id, name, cert_serial, agent_version)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority
`

type CreateNodeParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	Name         string    `json:"name"`
	CertSerial   string    `json:"cert_serial"`
	AgentVersion string    `json:"agent_version"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.OrgID,
		arg.Name,
		arg.CertSerial,
		arg.AgentVersion,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
	)
	return i, err
}

const getNodeByCertSerial = `-- name: GetNodeByCertSerial :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority FROM nodes
WHERE cert_serial = $1
`

// lint:cross-org — the mTLS client cert IS the identity; the org comes from the
// node row. Used to authorize every agent request.
func (q *Queries) GetNodeByCertSerial(ctx context.Context, certSerial string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByCertSerial, certSerial)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
	)
	return i, err
}

const getNodeByOrgName = `-- name: GetNodeByOrgName :one
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority FROM nodes
WHERE org_id = $1 AND name = $2
`

type GetNodeByOrgNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetNodeByOrgName(ctx context.Context, arg GetNodeByOrgNameParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByOrgName, arg.OrgID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CertSerial,
		&i.AgentVersion,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WgPublicKey,
		&i.Endpoint,
		&i.Capabilities,
		&i.PolicyDesyncSince,
		&i.PolicyReportedAt,
		&i.SiteID,
		&i.HubPriority,
	)
	return i, err
}

const getNodeHubPriority = `-- name: GetNodeHubPriority :one
SELECT hub_priority FROM nodes WHERE id = $1 AND org_id = $2
`

type GetNodeHubPriorityParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// lint:cross-org — org-scoped. The node's current hub_priority (nullable) so SetHubPriority can audit the
// old→new transition (S8.6 Slice 6 — the pin is a topology-consequential act).
func (q *Queries) GetNodeHubPriority(ctx context.Context, arg GetNodeHubPriorityParams) (*int32, error) {
	row := q.db.QueryRow(ctx, getNodeHubPriority, arg.ID, arg.OrgID)
	var hub_priority *int32
	err := row.Scan(&hub_priority)
	return hub_priority, err
}

const getOrgHubSet = `-- name: GetOrgHubSet :one
SELECT org_id, members, generation, updated_at FROM org_hub_set WHERE org_id = $1
`

// lint:cross-org — org-scoped by PK. The persisted transit-hub election (S8.6): ordered members + the D5
// generation. No rows until the first ReconcileHubSet.
func (q *Queries) GetOrgHubSet(ctx context.Context, orgID uuid.UUID) (OrgHubSet, error) {
	row := q.db.QueryRow(ctx, getOrgHubSet, orgID)
	var i OrgHubSet
	err := row.Scan(
		&i.OrgID,
		&i.Members,
		&i.Generation,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformSecret = `-- name: GetPlatformSecret :one
SELECT name, secret_sealed, public_pem, created_at, updated_at FROM platform_secrets WHERE name = $1
`

func (q *Queries) GetPlatformSecret(ctx context.Context, name string) (PlatformSecret, error) {
	row := q.db.QueryRow(ctx, getPlatformSecret, name)
	var i PlatformSecret
	err := row.Scan(
		&i.Name,
		&i.SecretSealed,
		&i.PublicPem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformSecret = `-- name: InsertPlatformSecret :exec
INSERT INTO platform_secrets (name, secret_sealed, public_pem)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO NOTHING
`

type InsertPlatformSecretParams struct {
	Name         string  `json:"name"`
	SecretSealed []byte  `json:"secret_sealed"`
	PublicPem    *string `json:"public_pem"`
}

// Create-if-absent; the caller reads-back on conflict. Never overwrites, so a
// concurrent boot can't clobber the CA (fail-loud-never-regenerate lives above).
func (q *Queries) InsertPlatformSecret(ctx context.Context, arg InsertPlatformSecretParams) error {
	_, err := q.db.Exec(ctx, insertPlatformSecret, arg.Name, arg.SecretSealed, arg.PublicPem)
	return err
}

const listActiveNodeIDsForOrg = `-- name: ListActiveNodeIDsForOrg :many
SELECT id FROM nodes
WHERE org_id = $1 AND status = 'active'
`

// S7.2 push targeting: every active gateway in the org. A policy change is org-wide,
// and member-removal can orphan a device whose node would drop out of a device-join
// query — so the push set is ALL active nodes (an unaffected node's re-fetch recompiles
// to identical bytes = reconcile no-op, so over-notifying is safe + correct).
func (q *Queries) ListActiveNodeIDsForOrg(ctx context.Context, orgID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveNodeIDsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailoverOrgs = `-- name: ListFailoverOrgs :many
SELECT org_id FROM org_hub_set WHERE array_length(members, 1) > 1
`

// lint:cross-org — CP-internal (the failover tick iterates every org). Orgs whose persisted hub set has
// MORE THAN ONE member — i.e. a pinned HA set with at least one standby; a single-hub org has nothing to
// fail over (S8.6 Slice 4).
func (q *Queries) ListFailoverOrgs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFailoverOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var org_id uuid.UUID
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodePeerStatusForOrg = `-- name: ListNodePeerStatusForOrg :many
SELECT nps.node_id, nps.public_key, nps.last_handshake_at, nps.rx_bytes, nps.tx_bytes, nps.updated_at
FROM node_peer_status nps
JOIN nodes n ON n.id = nps.node_id
WHERE n.org_id = $1
`

// lint:cross-org — org-scoped via the reporting node's org. Every gateway's node-peer telemetry for the
// org: the input to D3's per-hub freshness clock + the S8.5 L1 site-link card metrics (read path defined
// with the storage, consumed by S8.6 Slice 4 + Slice 6).
func (q *Queries) ListNodePeerStatusForOrg(ctx context.Context, orgID uuid.UUID) ([]NodePeerStatus, error) {
	rows, err := q.db.Query(ctx, listNodePeerStatusForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodePeerStatus{}
	for rows.Next() {
		var i NodePeerStatus
		if err := rows.Scan(
			&i.NodeID,
			&i.PublicKey,
			&i.LastHandshakeAt,
			&i.RxBytes,
			&i.TxBytes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, org_id, name, status, cert_serial, agent_version, enrolled_at, last_seen_at, revoked_at, created_at, updated_at, wg_public_key, endpoint, capabilities, policy_desync_since, policy_reported_at, site_id, hub_priority FROM nodes
WHERE org_id = $1
ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context, orgID uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CertSerial,
			&i.AgentVersion,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WgPublicKey,
			&i.Endpoint,
			&i.Capabilities,
			&i.PolicyDesyncSince,
			&i.PolicyReportedAt,
			&i.SiteID,
			&i.HubPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewNodeCert = `-- name: RenewNodeCert :exec
UPDATE nodes
SET cert_serial = $2, agent_version = $3, last_seen_at = now()
WHERE id = $1 AND status = 'active'
`

type RenewNodeCertParams struct {
	ID           uuid.UUID `json:"id"`
	CertSerial   string    `json:"cert_serial"`
	AgentVersion string    `json:"agent_version"`
}

// lint:cross-org — keyed by node id after the caller authorized via the current
// cert; renewal rotates the serial and stamps activity/version.
func (q *Queries) RenewNodeCert(ctx context.Context, arg RenewNodeCertParams) error {
	_, err := q.db.Exec(ctx, renewNodeCert, arg.ID, arg.CertSerial, arg.AgentVersion)
	return err
}

const revokeNode = `-- name: RevokeNode :exec
UPDATE nodes
SET status = 'revoked', revoked_at = now()
WHERE org_id = $1 AND id = $2
`

type RevokeNodeParams struct {
	OrgID uuid.UUID `json:"org_id"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) RevokeNode(ctx context.Context, arg RevokeNodeParams) error {
	_, err := q.db.Exec(ctx, revokeNode, arg.OrgID, arg.ID)
	return err
}

const setNodeHubPriority = `-- name: SetNodeHubPriority :execrows
UPDATE nodes SET hub_priority = $1 WHERE id = $2 AND org_id = $3
`

type SetNodeHubPriorityParams struct {
	HubPriority *int32    `json:"hub_priority"`
	NodeID      uuid.UUID `json:"node_id"`
	OrgID       uuid.UUID `json:"org_id"`
}

// lint:cross-org — org-scoped. The admin pin (S8.6 D1): a nullable rank; NULL clears the pin. Org-checked
// so a cross-org node id no-ops (0 rows -> typed 404 at the service).
func (q *Queries) SetNodeHubPriority(ctx context.Context, arg SetNodeHubPriorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeHubPriority, arg.HubPriority, arg.NodeID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNodeWGInfo = `-- name: SetNodeWGInfo :execrows
UPDATE nodes
SET wg_public_key = $1,
    endpoint = COALESCE(NULLIF($2::text, ''), nodes.endpoint),
    capabilities = $3::jsonb,
    last_seen_at = now(),
    -- S7.4b fold [1]: the applied-policy REPORT time (this write IS the report), distinct from
    -- last_seen_at (also bumped by DesiredState polls) — the desync freshness gate reads this.
    policy_reported_at = now()
WHERE id = $4 AND status = 'active'
`

type SetNodeWGInfoParams struct {
	WgPublicKey  string    `json:"wg_public_key"`
	Endpoint     string    `json:"endpoint"`
	Capabilities []byte    `json:"capabilities"`
	ID           uuid.UUID `json:"id"`
}

// lint:cross-org — keyed by id after cert authorization; the node reports its
// locally-generated WireGuard public key and its public endpoint (host:port that
// peer configs dial). Returns rows affected so the caller can distinguish a real
// write from a no-op (e.g. node revoked mid-report).
// endpoint uses COALESCE(NULLIF(...)) so an agent that reports an empty endpoint
// (env unset on a restart) never clobbers a previously-good value.
func (q *Queries) SetNodeWGInfo(ctx context.Context, arg SetNodeWGInfoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNodeWGInfo,
		arg.WgPublicKey,
		arg.Endpoint,
		arg.Capabilities,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampNodePolicyDesyncSince = `-- name: StampNodePolicyDesyncSince :exec
UPDATE nodes SET policy_desync_since = $3 WHERE id = $1 AND org_id = $2 AND policy_desync_since IS NULL
`

type StampNodePolicyDesyncSinceParams struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	PolicyDesyncSince pgtype.Timestamptz `json:"policy_desync_since"`
}

// S7.4b (X-4): stamp the term-3 desync ONSET, CONTROL-PLANE-ONLY, idempotent per episode —
// the WHERE ... IS NULL preserves the first onset (a repeated mismatch never re-stamps a
// newer time). Called from exactly one site (nodes.trackDesync); the value is the CP clock,
// never an agent string. org_id-scoped (tenant isolation).
func (q *Queries) StampNodePolicyDesyncSince(ctx context.Context, arg StampNodePolicyDesyncSinceParams) error {
	_, err := q.db.Exec(ctx, stampNodePolicyDesyncSince, arg.ID, arg.OrgID, arg.PolicyDesyncSince)
	return err
}

const touchNodeSeen = `-- name: TouchNodeSeen :exec
UPDATE nodes
SET last_seen_at = now()
WHERE id = $1
`

// lint:cross-org — keyed by id after cert authorization.
func (q *Queries) TouchNodeSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchNodeSeen, id)
	return err
}

const upsertOrgHubSet = `-- name: UpsertOrgHubSet :one
INSERT INTO org_hub_set (org_id, members, generation)
VALUES ($1, $2, 1)
ON CONFLICT (org_id) DO UPDATE
SET members = EXCLUDED.members,
    generation = CASE WHEN org_hub_set.members IS DISTINCT FROM EXCLUDED.members
                      THEN org_hub_set.generation + 1
                      ELSE org_hub_set.generation END,
    updated_at = now()
RETURNING org_id, members, generation, updated_at
`

type UpsertOrgHubSetParams struct {
	OrgID   uuid.UUID   `json:"org_id"`
	Members []uuid.UUID `json:"members"`
}

// lint:cross-org — org-scoped by PK. ATOMIC bump: the generation increments in the SAME statement ONLY
// when `members` actually changes (IS DISTINCT FROM) — so an idempotent re-election never bumps (no idle
// tick eroding the fence), and concurrent reconciles converge (whoever writes the same members second is a
// no-op bump). The D5 fencing token is monotonic + CP-persisted by construction here.
func (q *Queries) UpsertOrgHubSet(ctx context.Context, arg UpsertOrgHubSetParams) (OrgHubSet, error) {
	row := q.db.QueryRow(ctx, upsertOrgHubSet, arg.OrgID, arg.Members)
	var i OrgHubSet
	err := row.Scan(
		&i.OrgID,
		&i.Members,
		&i.Generation,
		&i.UpdatedAt,
	)
	return i, err
}
