// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ovpn.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertOVPNClientCert = `-- name: InsertOVPNClientCert :one

INSERT INTO ovpn_client_certs (org_id, device_id, serial, common_name, not_after)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, device_id, serial, common_name, not_after, issued_at, revoked_at
`

type InsertOVPNClientCertParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	DeviceID   uuid.UUID `json:"device_id"`
	Serial     string    `json:"serial"`
	CommonName string    `json:"common_name"`
	NotAfter   time.Time `json:"not_after"`
}

// S9.1 Slice 2: OpenVPN client-cert records. The issuance path records the cert identity so the
// Slice 5 revocation full-sweep + CRL have their source (B2). The private key is never stored.
func (q *Queries) InsertOVPNClientCert(ctx context.Context, arg InsertOVPNClientCertParams) (OvpnClientCert, error) {
	row := q.db.QueryRow(ctx, insertOVPNClientCert,
		arg.OrgID,
		arg.DeviceID,
		arg.Serial,
		arg.CommonName,
		arg.NotAfter,
	)
	var i OvpnClientCert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeviceID,
		&i.Serial,
		&i.CommonName,
		&i.NotAfter,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveOVPNClientCertsByOrg = `-- name: ListActiveOVPNClientCertsByOrg :many
SELECT id, org_id, device_id, serial, common_name, not_after, issued_at, revoked_at FROM ovpn_client_certs
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY issued_at
`

// The CRL source: every un-revoked, issued client cert for an org (Slice 5 builds the CRL from
// the COMPLEMENT — revoked serials — but this read backs the "live profiles" surface).
func (q *Queries) ListActiveOVPNClientCertsByOrg(ctx context.Context, orgID uuid.UUID) ([]OvpnClientCert, error) {
	rows, err := q.db.Query(ctx, listActiveOVPNClientCertsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OvpnClientCert{}
	for rows.Next() {
		var i OvpnClientCert
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeviceID,
			&i.Serial,
			&i.CommonName,
			&i.NotAfter,
			&i.IssuedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevokedOVPNSerialsByOrg = `-- name: ListRevokedOVPNSerialsByOrg :many
SELECT serial, not_after, revoked_at FROM ovpn_client_certs
WHERE org_id = $1 AND revoked_at IS NOT NULL AND not_after > now()
ORDER BY revoked_at
`

type ListRevokedOVPNSerialsByOrgRow struct {
	Serial    string             `json:"serial"`
	NotAfter  time.Time          `json:"not_after"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// The CRL entries for an org: serials revoked and not yet past expiry (an expired cert need not
// appear on the CRL — it's rejected on validity anyway). Slice 5 renders these into the CRL.
func (q *Queries) ListRevokedOVPNSerialsByOrg(ctx context.Context, orgID uuid.UUID) ([]ListRevokedOVPNSerialsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listRevokedOVPNSerialsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevokedOVPNSerialsByOrgRow{}
	for rows.Next() {
		var i ListRevokedOVPNSerialsByOrgRow
		if err := rows.Scan(&i.Serial, &i.NotAfter, &i.RevokedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOVPNClientCertsForDevice = `-- name: RevokeOVPNClientCertsForDevice :many
UPDATE ovpn_client_certs
SET revoked_at = now()
WHERE device_id = $1 AND revoked_at IS NULL
RETURNING serial
`

// The B2 sweep member: revoking a device revokes ALL its live OVPN certs, returning their serials
// so the caller pushes the updated CRL to the gateway (one sweep with address-release + status-clear).
// lint:cross-org — keyed by device_id inside the device-revoke transaction, which the caller has
// already org-authorized (mirrors RevokeDevicesForNode); the device->org binding is verified upstream.
func (q *Queries) RevokeOVPNClientCertsForDevice(ctx context.Context, deviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeOVPNClientCertsForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var serial string
		if err := rows.Scan(&serial); err != nil {
			return nil, err
		}
		items = append(items, serial)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
