// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ovpn.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOVPNCRLNumber = `-- name: BumpOVPNCRLNumber :one
INSERT INTO ovpn_crls (org_id, crl_pem, number) VALUES ($1, ''::bytea, 1)
ON CONFLICT (org_id) DO UPDATE SET number = ovpn_crls.number + 1
RETURNING number
`

// Atomically ALLOCATE the next monotonic per-org CRL number (D-S9.5-1: per-org, never a global counter).
// Concurrent rebuilds get DISTINCT numbers; the crl_pem is set immediately after by SetOVPNCRL for THIS
// number, so the highest-numbered (latest) CRL wins. On first revocation the placeholder crl_pem is empty
// for the microseconds until SetOVPNCRL runs — delivery treats an empty crl_pem as not-yet-ready.
func (q *Queries) BumpOVPNCRLNumber(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpOVPNCRLNumber, orgID)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const getOVPNCRLForOrg = `-- name: GetOVPNCRLForOrg :one
SELECT crl_pem, number FROM ovpn_crls WHERE org_id = $1
`

type GetOVPNCRLForOrgRow struct {
	CrlPem []byte `json:"crl_pem"`
	Number int64  `json:"number"`
}

// The org's current signed CRL (delivery reads this; empty crl_pem = not-yet-ready, skip this tick).
func (q *Queries) GetOVPNCRLForOrg(ctx context.Context, orgID uuid.UUID) (GetOVPNCRLForOrgRow, error) {
	row := q.db.QueryRow(ctx, getOVPNCRLForOrg, orgID)
	var i GetOVPNCRLForOrgRow
	err := row.Scan(&i.CrlPem, &i.Number)
	return i, err
}

const getOVPNServerCertForNode = `-- name: GetOVPNServerCertForNode :one
SELECT id, org_id, node_id, serial, cert_pem, sealed_key, not_after, issued_at FROM ovpn_server_certs WHERE node_id = $1
`

// lint:cross-org — keyed by node_id; the caller (DesiredState) already authorized the node via mTLS.
func (q *Queries) GetOVPNServerCertForNode(ctx context.Context, nodeID uuid.UUID) (OvpnServerCert, error) {
	row := q.db.QueryRow(ctx, getOVPNServerCertForNode, nodeID)
	var i OvpnServerCert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeID,
		&i.Serial,
		&i.CertPem,
		&i.SealedKey,
		&i.NotAfter,
		&i.IssuedAt,
	)
	return i, err
}

const insertOVPNClientCert = `-- name: InsertOVPNClientCert :one

INSERT INTO ovpn_client_certs (org_id, device_id, serial, common_name, not_after)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, device_id, serial, common_name, not_after, issued_at, revoked_at
`

type InsertOVPNClientCertParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	DeviceID   uuid.UUID `json:"device_id"`
	Serial     string    `json:"serial"`
	CommonName string    `json:"common_name"`
	NotAfter   time.Time `json:"not_after"`
}

// S9.1 Slice 2: OpenVPN client-cert records. The issuance path records the cert identity so the
// Slice 5 revocation full-sweep + CRL have their source (B2). The private key is never stored.
func (q *Queries) InsertOVPNClientCert(ctx context.Context, arg InsertOVPNClientCertParams) (OvpnClientCert, error) {
	row := q.db.QueryRow(ctx, insertOVPNClientCert,
		arg.OrgID,
		arg.DeviceID,
		arg.Serial,
		arg.CommonName,
		arg.NotAfter,
	)
	var i OvpnClientCert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeviceID,
		&i.Serial,
		&i.CommonName,
		&i.NotAfter,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertOVPNServerCert = `-- name: InsertOVPNServerCert :one
INSERT INTO ovpn_server_certs (org_id, node_id, serial, cert_pem, sealed_key, not_after)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, node_id, serial, cert_pem, sealed_key, not_after, issued_at
`

type InsertOVPNServerCertParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	NodeID    uuid.UUID `json:"node_id"`
	Serial    string    `json:"serial"`
	CertPem   string    `json:"cert_pem"`
	SealedKey string    `json:"sealed_key"`
	NotAfter  time.Time `json:"not_after"`
}

func (q *Queries) InsertOVPNServerCert(ctx context.Context, arg InsertOVPNServerCertParams) (OvpnServerCert, error) {
	row := q.db.QueryRow(ctx, insertOVPNServerCert,
		arg.OrgID,
		arg.NodeID,
		arg.Serial,
		arg.CertPem,
		arg.SealedKey,
		arg.NotAfter,
	)
	var i OvpnServerCert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeID,
		&i.Serial,
		&i.CertPem,
		&i.SealedKey,
		&i.NotAfter,
		&i.IssuedAt,
	)
	return i, err
}

const listActiveOVPNClientCertsByOrg = `-- name: ListActiveOVPNClientCertsByOrg :many
SELECT id, org_id, device_id, serial, common_name, not_after, issued_at, revoked_at FROM ovpn_client_certs
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY issued_at
`

// The CRL source: every un-revoked, issued client cert for an org (Slice 5 builds the CRL from
// the COMPLEMENT — revoked serials — but this read backs the "live profiles" surface).
func (q *Queries) ListActiveOVPNClientCertsByOrg(ctx context.Context, orgID uuid.UUID) ([]OvpnClientCert, error) {
	rows, err := q.db.Query(ctx, listActiveOVPNClientCertsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OvpnClientCert{}
	for rows.Next() {
		var i OvpnClientCert
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeviceID,
			&i.Serial,
			&i.CommonName,
			&i.NotAfter,
			&i.IssuedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevokedOVPNSerialsByOrg = `-- name: ListRevokedOVPNSerialsByOrg :many
SELECT serial, not_after, revoked_at FROM ovpn_client_certs
WHERE org_id = $1 AND revoked_at IS NOT NULL AND not_after > now()
ORDER BY revoked_at
`

type ListRevokedOVPNSerialsByOrgRow struct {
	Serial    string             `json:"serial"`
	NotAfter  time.Time          `json:"not_after"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// The CRL entries for an org: serials revoked and not yet past expiry (an expired cert need not
// appear on the CRL — it's rejected on validity anyway). Slice 5 renders these into the CRL.
func (q *Queries) ListRevokedOVPNSerialsByOrg(ctx context.Context, orgID uuid.UUID) ([]ListRevokedOVPNSerialsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listRevokedOVPNSerialsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevokedOVPNSerialsByOrgRow{}
	for rows.Next() {
		var i ListRevokedOVPNSerialsByOrgRow
		if err := rows.Scan(&i.Serial, &i.NotAfter, &i.RevokedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOVPNClientCertsForDevice = `-- name: RevokeOVPNClientCertsForDevice :many
UPDATE ovpn_client_certs
SET revoked_at = now()
WHERE device_id = $1 AND revoked_at IS NULL
RETURNING serial
`

// The B2 sweep member: revoking a device revokes ALL its live OVPN certs, returning their serials
// so the caller pushes the updated CRL to the gateway (one sweep with address-release + status-clear).
// lint:cross-org — keyed by device_id inside the device-revoke transaction, which the caller has
// already org-authorized (mirrors RevokeDevicesForNode); the device->org binding is verified upstream.
func (q *Queries) RevokeOVPNClientCertsForDevice(ctx context.Context, deviceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeOVPNClientCertsForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var serial string
		if err := rows.Scan(&serial); err != nil {
			return nil, err
		}
		items = append(items, serial)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOVPNClientCertsForNode = `-- name: RevokeOVPNClientCertsForNode :many
UPDATE ovpn_client_certs SET revoked_at = now()
WHERE device_id IN (SELECT id FROM devices WHERE node_id = $1 AND deleted_at IS NULL) AND revoked_at IS NULL
RETURNING org_id
`

// The node-revoke sweep member: revoking a NODE revokes all its devices (RevokeDevicesForNode), so their
// live OVPN client certs are revoked too (revoked_at), returning the affected orgs so the shared RebuildCRL
// runs once per org. lint:cross-org — keyed by node_id inside the node-revoke transaction (org-authorized
// upstream, mirrors RevokeDevicesForNode).
func (q *Queries) RevokeOVPNClientCertsForNode(ctx context.Context, nodeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeOVPNClientCertsForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var org_id uuid.UUID
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOVPNCRL = `-- name: SetOVPNCRL :exec
UPDATE ovpn_crls SET crl_pem = $2, updated_at = now() WHERE org_id = $1 AND number = $3
`

type SetOVPNCRLParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	CrlPem []byte    `json:"crl_pem"`
	Number int64     `json:"number"`
}

// Store the signed CRL for the number THIS rebuild allocated. WHERE number = $3 so a concurrent rebuild
// that bumped past us (higher number, later revocation snapshot) is authoritative — our lower-numbered CRL
// is simply not stored (the latest full-set CRL wins).
func (q *Queries) SetOVPNCRL(ctx context.Context, arg SetOVPNCRLParams) error {
	_, err := q.db.Exec(ctx, setOVPNCRL, arg.OrgID, arg.CrlPem, arg.Number)
	return err
}
