// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// lint:cross-org — authorized by the invitation id obtained via its token, not
	// by org scope. Single-use: only transitions a pending, unexpired invite.
	AcceptInvitation(ctx context.Context, id uuid.UUID) (Invitation, error)
	// ── group_members ───────────────────────────────────────────────────────────────
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	// The browser leg binds the human's identity to the pending device code.
	ApproveCliDeviceCode(ctx context.Context, arg ApproveCliDeviceCodeParams) (int64, error)
	ChangeMemberRole(ctx context.Context, arg ChangeMemberRoleParams) (Membership, error)
	// Single-use + purpose-bound: only matches an unconsumed, unexpired token of the
	// given purpose. A reset token therefore cannot be consumed as a verification
	// token and vice-versa.
	ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (AuthToken, error)
	// Atomic single-use consume; returns the row only on the FIRST valid redemption.
	ConsumeCliAuthCode(ctx context.Context, codeHash []byte) (CliAuthCode, error)
	// Atomic single-use consume of an APPROVED device code.
	ConsumeCliDeviceCode(ctx context.Context, deviceCodeHash []byte) (CliDeviceCode, error)
	// lint:cross-org — the token itself is the credential; the org comes from the
	// returned row. Single-use + expiring.
	ConsumeJoinToken(ctx context.Context, tokenHash []byte) (NodeJoinToken, error)
	CountActiveDevicesByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountActiveDevicesForUser(ctx context.Context, arg CountActiveDevicesForUserParams) (int64, error)
	CountActiveNodesByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	// Org roster size. Joins users to exclude soft-deleted accounts (whose
	// membership row survives a soft-delete); deactivated members are still on the
	// roster, so they are intentionally counted.
	CountMembersByOrg(ctx context.Context, orgID uuid.UUID) (int64, error)
	// "Seen recently": last handshake within the window ($2 = now - OnlineWindow),
	// an S3.6-style online approximation. The boundary is inclusive (>=) to match
	// deviceOnline's `time.Since(h) <= threshold`. Requires an ACTIVE owner too: a
	// deactivated user's peers are offboarded from the data plane (they fall out of
	// the node's desired state) even though the device row stays 'active', so
	// counting them as "online" would be dishonest.
	CountOnlineDevicesByOrg(ctx context.Context, arg CountOnlineDevicesByOrgParams) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	// lint:cross-org — spans a user's orgs to protect the last-owner invariant on
	// global deactivation; each row's org_id is used in the correlated subquery.
	CountOrgsWhereSoleOwner(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOwners(ctx context.Context, orgID uuid.UUID) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateCliAuthCode(ctx context.Context, arg CreateCliAuthCodeParams) (CliAuthCode, error)
	// CLI credential flow (S5.1). All secrets arrive here PRE-HASHED (sha-256); the
	// raw token/code never reaches SQL. Consumption is a single atomic UPDATE so a
	// code can never be redeemed twice (no check-then-consume window).
	CreateCliCredential(ctx context.Context, arg CreateCliCredentialParams) (CliCredential, error)
	CreateCliDeviceCode(ctx context.Context, arg CreateCliDeviceCodeParams) (CliDeviceCode, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateDomainClaim(ctx context.Context, arg CreateDomainClaimParams) (DomainClaim, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (NodeJoinToken, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// ── policy_rules (allow grants) ─────────────────────────────────────────────────
	CreatePolicyRule(ctx context.Context, arg CreatePolicyRuleParams) (PolicyRule, error)
	// ── resources (static destinations) ─────────────────────────────────────────────
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Zero Trust policy model (S7.1). Enterprise feature; model-only (no data plane).
	// All tenant tables scope by org_id (tenant-lint). Policy objects are hard-deleted
	// (FK ON DELETE CASCADE), so there is no deleted_at filter here.
	// ── user_groups (the rule SUBJECT) ──────────────────────────────────────────────
	CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UserGroup, error)
	// lint:cross-org — keyed by device_id (the caller already authorized the device
	// via its org). Clears a device's live status (on revoke) so a revoked device
	// never reports stale online/handshake via the API.
	DeleteDeviceStatus(ctx context.Context, deviceID uuid.UUID) error
	DeletePolicyRule(ctx context.Context, arg DeletePolicyRuleParams) (int64, error)
	DeleteResource(ctx context.Context, arg DeleteResourceParams) (int64, error)
	DeleteUserGroup(ctx context.Context, arg DeleteUserGroupParams) (int64, error)
	// Returns a fresh time-ordered UUIDv7 from the database. Demonstrates the sqlc
	// pipeline and the uuid override; callers may also generate v7 ids in Go.
	GenerateID(ctx context.Context) (uuid.UUID, error)
	// Active = not revoked and not expired. Expired/revoked rows fail auth closed.
	GetActiveCliCredentialByHash(ctx context.Context, tokenHash []byte) (CliCredential, error)
	// Any state (auth needs to distinguish "expired" from "unknown" for the CLI's
	// credential_expired UX line).
	GetCliCredentialByHash(ctx context.Context, tokenHash []byte) (CliCredential, error)
	GetCliDeviceCodeByDeviceHash(ctx context.Context, deviceCodeHash []byte) (CliDeviceCode, error)
	GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error)
	GetDomainClaim(ctx context.Context, arg GetDomainClaimParams) (DomainClaim, error)
	// lint:cross-org — SSO callback resolves the config by (provider, client_id)
	// before an org context exists; org_id is a column on the returned row.
	GetEnabledSSOConfigByProvider(ctx context.Context, arg GetEnabledSSOConfigByProviderParams) (SsoConfig, error)
	// lint:cross-org — the token hash IS the authorization key; lookup is by token,
	// not org. Callers must still check expires_at/accepted_at/revoked_at (single-use).
	GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (Invitation, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// lint:cross-org — the mTLS client cert IS the identity; the org comes from the
	// node row. Used to authorize every agent request.
	GetNodeByCertSerial(ctx context.Context, certSerial string) (Node, error)
	GetNodeByOrgName(ctx context.Context, arg GetNodeByOrgNameParams) (Node, error)
	// Verifies a node belongs to the org (id+org scoped) before a device attaches to it.
	GetOrgNode(ctx context.Context, arg GetOrgNodeParams) (Node, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPlatformSecret(ctx context.Context, name string) (PlatformSecret, error)
	GetResource(ctx context.Context, arg GetResourceParams) (Resource, error)
	GetSSOConfig(ctx context.Context, arg GetSSOConfigParams) (SsoConfig, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserGroup(ctx context.Context, arg GetUserGroupParams) (UserGroup, error)
	// lint:cross-org — JIT resolves the capturing org from an email domain before an
	// org context exists; org_id is a column on the returned row. Only verified
	// claims are returned (partial unique index guarantees at most one).
	GetVerifiedClaimForDomain(ctx context.Context, domain string) (DomainClaim, error)
	// audit_logs is append-only: there are intentionally NO update or delete queries
	// here, and the DB enforces it (see 0002 triggers).
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	// Create-if-absent; the caller reads-back on conflict. Never overwrites, so a
	// concurrent boot can't clobber the CA (fail-loud-never-regenerate lives above).
	InsertPlatformSecret(ctx context.Context, arg InsertPlatformSecretParams) error
	// Consume all outstanding tokens of a purpose for a user (e.g. before issuing a
	// new password-reset token, so only the latest is valid).
	InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error
	// The org's live tunnel allocations (flat pool, across all nodes) WITH the owning
	// device (id, name). The SINGLE definition of "live allocation" — used by BOTH
	// device-create's lowest-free choice AND resize's orphan check/409 objects, so
	// there are no two filtered reads to drift apart. Read under the org advisory
	// lock so allocation and resize serialize on the same snapshot.
	ListActiveDeviceAllocations(ctx context.Context, orgID uuid.UUID) ([]ListActiveDeviceAllocationsRow, error)
	// ── compiler inputs ─────────────────────────────────────────────────────────────
	// Every active device owned by an active user, org-wide (all nodes) — the compiler
	// resolves group destinations to these devices' /32s and keys allows by src /32.
	ListActiveDevicesForOrg(ctx context.Context, orgID uuid.UUID) ([]ListActiveDevicesForOrgRow, error)
	// lint:cross-org — keyed by node_id after mTLS cert authorization (the agent
	// fetches the peers for its own node). A peer is present only while BOTH the
	// device is active AND its owning user is active — so deactivating a user drops
	// their peers from every node's desired state (and reactivation restores them).
	ListActivePeersForNode(ctx context.Context, nodeID uuid.UUID) ([]ListActivePeersForNodeRow, error)
	// Org-scoped audit feed with optional filters (actor / action / date range) and
	// KEYSET pagination on (created_at, id) DESC. Every filter + cursor param is
	// nullable, so the S4.3 dashboard passes none (latest N). The cursor is written
	// as a ROW-VALUE comparison so it plans against (org_id, created_at DESC, id DESC)
	// rather than an OR-expansion the planner can't use.
	ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error)
	ListCliCredentialsForUser(ctx context.Context, userID uuid.UUID) ([]CliCredential, error)
	ListDevicesByOrg(ctx context.Context, orgID uuid.UUID) ([]ListDevicesByOrgRow, error)
	ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]ListDevicesByUserRow, error)
	ListDomainClaims(ctx context.Context, orgID uuid.UUID) ([]DomainClaim, error)
	ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error)
	// Compiler input: every (group, user) pair in the org.
	ListGroupMembershipsByOrg(ctx context.Context, orgID uuid.UUID) ([]ListGroupMembershipsByOrgRow, error)
	ListInvitations(ctx context.Context, orgID uuid.UUID) ([]Invitation, error)
	ListMembershipsByOrg(ctx context.Context, orgID uuid.UUID) ([]Membership, error)
	// lint:cross-org — intentionally spans orgs: a user's memberships across all
	// their organizations (used to resolve which orgs a principal belongs to).
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]Membership, error)
	// lint:cross-org — keyed by user_id; used to find which nodes to push after a
	// user's peers change (create/revoke/deactivate). Not org-scoped: a user's
	// devices may span orgs and all affected nodes must be nudged to reconcile.
	ListNodeIDsForUserActiveDevices(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	ListNodes(ctx context.Context, orgID uuid.UUID) ([]Node, error)
	// The org roster for the Users page: membership joined to the user record so the
	// UI has name/email/status/verified in one query. Soft-deleted users are
	// excluded (their membership row survives a soft-delete); deactivated members
	// stay on the roster (status carries that).
	ListOrgMembersWithUser(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersWithUserRow, error)
	// Admin/system listing of all orgs; user-facing listing uses
	// ListOrganizationsForUser (membership-scoped).
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error)
	ListPolicyRulesByOrg(ctx context.Context, orgID uuid.UUID) ([]PolicyRule, error)
	ListResourcesByOrg(ctx context.Context, orgID uuid.UUID) ([]Resource, error)
	ListUserGroupsByOrg(ctx context.Context, orgID uuid.UUID) ([]UserGroup, error)
	// lint:cross-org — a transaction-scoped advisory lock on an arbitrary key (a
	// user id or org id, passed as text). Create takes BOTH (in sorted order, so no
	// deadlock) to make the per-user cap check AND the org-wide IP allocation atomic
	// against concurrent creates.
	//
	// TWO CLIENTS, both load-bearing: (1) device allocation (per-org mutual
	// exclusion); (2) CIDR resize (S4.5b) — ResizePool takes the org key so its
	// orphan check can't race a concurrent allocation during the resize window. A
	// future S3.5 refactor that rescopes/weakens this lock (per-device keys, etc.)
	// MUST keep resize and allocation contending on the SAME per-org key, or it
	// silently reopens that race — see TestResizeAllocationRace (the red-without-lock
	// guard). Resize takes only the org key; allocation takes {owner,org} sorted;
	// resize never waits on the owner key, so no inversion/deadlock.
	LockDeviceKey(ctx context.Context, dollar_1 string) error
	MarkDomainVerified(ctx context.Context, arg MarkDomainVerifiedParams) (DomainClaim, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error)
	RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error)
	// lint:cross-org — keyed by node id after the caller authorized via the current
	// cert; renewal rotates the serial and stamps activity/version.
	RenewNodeCert(ctx context.Context, arg RenewNodeCertParams) error
	// The SWEEP: password reset and account deactivation kill every live CLI
	// credential exactly like they kill sessions (a surviving credential would be a
	// back door around the sweep).
	RevokeAllCliCredentialsForUser(ctx context.Context, userID uuid.UUID) error
	// Self-scoped: the WHERE user_id makes another user's credential unreachable
	// (idempotent 204 semantics; no existence leak).
	RevokeCliCredential(ctx context.Context, arg RevokeCliCredentialParams) (int64, error)
	// Returns the gateway node_id (for the push) so the caller needs no extra read;
	// pgx.ErrNoRows means the device was not active (already revoked / wrong org).
	// Clears assigned_ip to release the address explicitly (rather than relying on
	// every reader to also filter status='active').
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (uuid.UUID, error)
	// lint:cross-org — keyed by node_id; when a node is revoked its peers can no
	// longer reach a gateway, so they are revoked too (no dangling active devices).
	RevokeDevicesForNode(ctx context.Context, nodeID uuid.UUID) (int64, error)
	RevokeInvitationByOrgEmail(ctx context.Context, arg RevokeInvitationByOrgEmailParams) (int64, error)
	RevokeNode(ctx context.Context, arg RevokeNodeParams) error
	// lint:cross-org — keyed by id after cert authorization; the node reports its
	// locally-generated WireGuard public key and its public endpoint (host:port that
	// peer configs dial). Returns rows affected so the caller can distinguish a real
	// write from a no-op (e.g. node revoked mid-report).
	// endpoint uses COALESCE(NULLIF(...)) so an agent that reports an empty endpoint
	// (env unset on a restart) never clobbers a previously-good value.
	SetNodeWGInfo(ctx context.Context, arg SetNodeWGInfoParams) (int64, error)
	// ── org enforcement mode ────────────────────────────────────────────────────────
	SetOrgZeroTrustMode(ctx context.Context, arg SetOrgZeroTrustModeParams) (Organization, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	SoftDeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error)
	// When a user joins an org another way (e.g. domain-capture JIT), pending
	// invites for that (org, email) become moot — revoke them so they can't be
	// accepted into a second membership attempt.
	SupersedePendingInvites(ctx context.Context, arg SupersedePendingInvitesParams) error
	// Verification loss: clear verified_at so the domain stops capturing (the claim
	// is NOT deleted — the org keeps its pending claim and can re-verify).
	SuspendDomainClaim(ctx context.Context, arg SuspendDomainClaimParams) error
	TouchCliCredentialUsed(ctx context.Context, id uuid.UUID) error
	TouchDomainCheckedAt(ctx context.Context, arg TouchDomainCheckedAtParams) error
	// lint:cross-org — keyed by id after cert authorization.
	TouchNodeSeen(ctx context.Context, id uuid.UUID) error
	// Resize the org tunnel pool. The service refuses a shrink that would orphan
	// live allocations (checked in Go before calling this); this just persists it.
	UpdateOrgPoolCidr(ctx context.Context, arg UpdateOrgPoolCidrParams) (Organization, error)
	// Slug is immutable after creation (S1.2); only name is updatable here.
	UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) (UserGroup, error)
	// lint:cross-org — keyed by node_id (agent is cert-authorized) + pubkey. Batched
	// (pgx.Batch) so a whole report is a single round-trip; no per-peer write
	// amplification and the write lands on the lean status table, not the devices
	// row. Maps pubkey->active device on this node; an unknown pubkey is a no-op.
	// rx/tx are raw gauges.
	UpsertDeviceStatus(ctx context.Context, arg []UpsertDeviceStatusParams) *UpsertDeviceStatusBatchResults
	// Idempotent on (org_id, user_id).
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error)
	// Used by the seed with a fixed id; idempotent. Also clears deleted_at so
	// re-seeding restores a previously soft-deleted demo org to a clean live state.
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (Organization, error)
	UpsertSSOConfig(ctx context.Context, arg UpsertSSOConfigParams) (SsoConfig, error)
	// Used by the seed with a fixed id; idempotent.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
