// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const generateID = `-- name: GenerateID :one
SELECT uuid_generate_v7() AS id
`

// Returns a fresh time-ordered UUIDv7 from the database. Demonstrates the sqlc
// pipeline and the uuid override; callers may also generate v7 ids in Go.
func (q *Queries) GenerateID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, generateID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
