/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports process liveness. No external dependencies are checked.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a local account (sends a verification email) */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify credentials
         * @description S2.1 verifies credentials; S2.2 establishes the session cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an email address with a token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password-reset email */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password using a reset token */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public deployment metadata (edition, enabled SSO providers)
         * @description Lets the SPA gate edition-only UI (e.g. hide SSO in the open build) without a build-time bundle fork.
         */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the current user's email-verification link
         * @description Idempotent; a no-op (still 202) if already verified. Requires a session.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current authenticated user
         * @description Returns the session's user so the SPA can rehydrate auth on load; 401 if there is no valid session.
         */
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session
         * @description Idempotent — clears the cookie and revokes the session if present.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin an SSO login (enterprise) */
        get: operations["startSsoLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sso/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSO callback (enterprise) */
        get: operations["ssoCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/sso/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                provider: "google" | "microsoft";
            };
            cookie?: never;
        };
        /** Read an SSO provider's config (enterprise) — never returns the secret */
        get: operations["getSsoConfig"];
        /** Configure an SSO provider for an organization (enterprise) */
        put: operations["setSsoConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a one-time CLI authorization code (browser leg)
         * @description COOKIE-SESSION ONLY (argued exception to bearer≡cookie): minting a new credential from an existing bearer credential would be self-replication — a stolen token could outlive its expiry by re-minting. The browser session is the human checkpoint. Verified email required. The redirect_uri must be a loopback (http://127.0.0.1:<port>/callback or http://[::1]:<port>/callback, any port, exactly that path — never a hostname). The code is single-use, expires in 60s, and is bound to this exact redirect_uri + PKCE challenge.
         *
         */
        post: operations["cliAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a one-time code (+ PKCE verifier) for a CLI credential
         * @description Public (the CLI holds no credential yet). The exchange requires the code, the PKCE verifier matching the challenge presented at authorize, and the EXACT redirect_uri the code was bound to. Any mismatch, reuse, or expiry → 400 invalid_grant. The credential is returned EXACTLY ONCE.
         *
         */
        post: operations["cliToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's CLI credentials (metadata only — never tokens) */
        get: operations["listCliCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/credentials/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the caller's CLI credentials (immediate)
         * @description Self-scoped (a caller revokes only their own credential). Allowed unverified — revoking a credential is logout-class, not org-mutating.
         *
         */
        delete: operations["revokeCliCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the device-code fallback (browserless hosts)
         * @description Public. Returns a short user_code the user enters at verification_uri from any browser, and a device_code the CLI polls with. Same hygiene class as authorization codes — hashed at rest, single-use, short TTL.
         *
         */
        post: operations["cliDeviceStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/device/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a device-code login (browser leg)
         * @description COOKIE-SESSION ONLY (same argued exception as cliAuthorize) + verified email required — this is the human checkpoint of the device flow.
         *
         */
        post: operations["cliDeviceApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cli/device/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll for the device-flow credential
         * @description Public. 400 authorization_pending until approved; expired/consumed codes → 400 invalid_grant. On approval the credential is returned EXACTLY ONCE.
         *
         */
        post: operations["cliDeviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll a tunnex-node agent with a join token */
        post: operations["enrollAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List enrolled nodes */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/nodes/join-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a single-use node join token */
        post: operations["issueJoinToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/nodes/{nodeId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a node (renewal will be refused) */
        post: operations["revokeNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** Dashboard overview — counts + recent activity */
        get: operations["getOrgOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** The org's audit log — filterable, keyset-paginated (read-only) */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List devices (own devices for members; all for admins) */
        get: operations["listDevices"];
        put?: never;
        /** Create a device/peer bound to the owning user */
        post: operations["createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/devices/{deviceId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                deviceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a device (peer removed from the gateway within seconds) */
        post: operations["revokeDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List user-groups (enterprise) */
        get: operations["listGroups"];
        put?: never;
        /** Create a user-group (enterprise) */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user-group (enterprise) */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Rename / re-describe a user-group (enterprise) */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
            };
            cookie?: never;
        };
        /** List a group's members (enterprise) */
        get: operations["listGroupMembers"];
        put?: never;
        /** Add a member to a group (enterprise) */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/groups/{groupId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a group (enterprise) */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List policy resources (enterprise) */
        get: operations["listResources"];
        put?: never;
        /** Create a policy resource (enterprise) */
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a policy resource (enterprise) */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        /** Update a policy resource (enterprise) */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List allow-rules (enterprise) */
        get: operations["listPolicyRules"];
        put?: never;
        /** Create an allow-rule (enterprise) */
        post: operations["createPolicyRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/policies/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an allow-rule (enterprise) */
        delete: operations["deletePolicyRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/zero-trust-mode": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** Get the org enforcement mode (enterprise) */
        get: operations["getZeroTrustMode"];
        /** Set the org enforcement mode — enabling turns on default-deny (enterprise) */
        put: operations["setZeroTrustMode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a user to the organization */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/invitations/resend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend an invitation (new token, old invalidated) */
        post: operations["resendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/invitations/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a pending invitation */
        post: operations["revokeInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List the organization's members (roster incl. deactivated) */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/members/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Change a member's role (RBAC-gated; refuses demoting the last owner) */
        put: operations["changeMemberRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/members/{userId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a member's account (freezes access, revokes sessions) */
        post: operations["deactivateMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/members/{userId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate a deactivated member */
        post: operations["reactivateMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim an email domain for capture (enterprise) */
        post: operations["createDomainClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/domains/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a claimed domain via its DNS TXT record (enterprise) */
        post: operations["verifyDomainClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations
         * @description Lists the organizations the authenticated user belongs to.
         */
        get: operations["listOrganizations"];
        put?: never;
        /**
         * Create an organization
         * @description Creates an organization. In the open edition this fails with
         *     `org_limit_reached` once one organization exists; the enterprise build
         *     allows multiple.
         *
         */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** Get an organization */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        /** Soft-delete an organization */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        /** Update organization settings (name only; slug is immutable) */
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/pool-cidr": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Resize the org's WireGuard address pool (grow-superset or shrink-subset) */
        put: operations["resizePool"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Liveness status.
             * @enum {string}
             */
            status: "ok";
            /**
             * @description Reporting service name.
             * @example tunnex-api
             */
            service: string;
            /** @description Correlation ID for this request. */
            request_id?: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @description The org's flat WireGuard address pool (IPv4 CIDR). */
            pool_cidr: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PoolCidrRequest: {
            /** @description New pool CIDR (IPv4). Must contain or be contained by the current range. */
            cidr: string;
        };
        UserGroup: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GroupRequest: {
            name: string;
            description?: string;
        };
        GroupMember: {
            /** Format: uuid */
            user_id: string;
            email: string;
            name: string;
            /** Format: date-time */
            added_at: string;
        };
        AddGroupMemberRequest: {
            /** Format: uuid */
            user_id: string;
        };
        Resource: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            name: string;
            /** @description Destination prefix (e.g. 10.0.5.0/24, 0.0.0.0/0). */
            cidr: string;
            /** @enum {string} */
            protocol: "any" | "tcp" | "udp";
            port_low?: number | null;
            port_high?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ResourceRequest: {
            name: string;
            cidr: string;
            /** @enum {string} */
            protocol: "any" | "tcp" | "udp";
            port_low?: number | null;
            port_high?: number | null;
        };
        PolicyRule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            src_group_id: string;
            /** @enum {string} */
            dst_kind: "resource" | "group";
            /** Format: uuid */
            dst_resource_id?: string | null;
            /** Format: uuid */
            dst_group_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreatePolicyRuleRequest: {
            /** Format: uuid */
            src_group_id: string;
            /** @enum {string} */
            dst_kind: "resource" | "group";
            /**
             * Format: uuid
             * @description Required when dst_kind=resource.
             */
            dst_resource_id?: string | null;
            /**
             * Format: uuid
             * @description Required when dst_kind=group.
             */
            dst_group_id?: string | null;
        };
        ZeroTrustMode: {
            /**
             * @description off = legacy blanket mesh; enforcing = default-deny + compiled allows.
             * @enum {string}
             */
            mode: "off" | "enforcing";
            /** @description On ENABLING enforcing (PUT only), the full-tunnel devices whose internet egress becomes policy-governed by the flip — the blast radius for the warn-and-confirm. The server obeys regardless; this is the honest count + names. Absent/empty when disabling or when none are affected. State name for these = egress_policy_denied (distinct from gateway_no_egress: the gateway CAN egress, policy is denying it).
             *      */
            affected_full_tunnel_devices?: components["schemas"]["AffectedDevice"][];
        };
        AffectedDevice: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Orphan: {
            /** Format: uuid */
            device_id: string;
            name: string;
            assigned_ip: string;
            /** @enum {string} */
            reason: "out_of_range" | "reserved_collision";
        };
        ResizeConflict: {
            orphan_count: number;
            orphans: components["schemas"]["Orphan"][];
        };
        CreateOrganizationRequest: {
            name: string;
            slug: string;
        };
        /** @description Only the name is mutable; the slug is fixed at creation. */
        UpdateOrganizationRequest: {
            name: string;
        };
        CliAuthorizeRequest: {
            /** @description Loopback only — http://127.0.0.1:<port>/callback or http://[::1]:<port>/callback (any port, exactly that path; hostnames incl. "localhost" are refused — DNS-spoofable).
             *      */
            redirect_uri: string;
            /** @description PKCE S256 challenge (base64url SHA-256 of the CLI's verifier). */
            code_challenge: string;
            /** @description Echoed to the loopback callback verbatim (CLI-side correlation/CSRF). */
            state: string;
        };
        CliAuthorizeResponse: {
            /** @description One-time authorization code (single-use, hashed at rest). */
            code: string;
            state: string;
            /** @description Code lifetime in seconds (60). */
            expires_in: number;
        };
        CliTokenRequest: {
            code: string;
            code_verifier: string;
            /** @description Must EXACTLY match the redirect the code was bound to at mint. */
            redirect_uri: string;
        };
        CliTokenResponse: {
            /** @description The dedicated CLI bearer credential, prefixed tnx_ (secret-scanner matchable). Shown exactly once; stored hashed; send as "Authorization: Bearer <token>".
             *      */
            token: string;
            /**
             * Format: date-time
             * @description Absolute expiry (90 days).
             */
            expires_at: string;
            /** @description Keyed 12-hex proof-of-secret; matches audit rows. */
            fingerprint: string;
        };
        CliCredential: {
            /** Format: uuid */
            id: string;
            /** @description Client-supplied label (e.g. hostname) or a default. */
            name: string;
            fingerprint: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string;
            /** Format: date-time */
            expires_at: string;
        };
        CliDeviceStartResponse: {
            /** @description Poll credential; never shown to the user. */
            device_code: string;
            /** @description Short human code entered in the browser. */
            user_code: string;
            verification_uri: string;
            /** @description Minimum poll interval in seconds. */
            interval: number;
            expires_in: number;
        };
        CliDeviceApproveRequest: {
            user_code: string;
        };
        CliDeviceTokenRequest: {
            device_code: string;
        };
        GenericMessage: {
            message: string;
        };
        InviteCreated: {
            message: string;
            /** @description Raw one-time accept token. The dashboard builds the accept link (origin + /accept-invite?token=…) for the admin to hand to the invitee — the SMTP-less delivery path. Also emailed when SMTP is configured. Shown once; not retrievable later. */
            invite_token: string;
        };
        SsoRedirect: {
            redirect_url: string;
        };
        EnrollRequest: {
            join_token: string;
            /** @description PEM-encoded certificate signing request */
            csr: string;
            node_name: string;
            agent_version: string;
            protocol_version: number;
        };
        EnrollResponse: {
            /** Format: uuid */
            node_id: string;
            /** @description PEM agent certificate */
            certificate: string;
            /** @description PEM CA certificate */
            ca_certificate: string;
        };
        Node: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "active" | "revoked";
            agent_version: string;
            /** Format: date-time */
            enrolled_at: string;
            /** Format: date-time */
            last_seen_at?: string;
            /** @description Zero Trust (enterprise): the gateway's policy apply has been FAILING beyond the stale window — it is enforcing an out-of-date ruleset. Alarm-worthy. */
            policy_stale?: boolean;
            /** @description Zero Trust (enterprise): the policy IN FORCE matches what the control plane would push now. false = the gateway hasn't applied the latest policy yet (syncing, or silently stale). */
            policy_synced?: boolean;
        };
        JoinTokenRequest: {
            node_name?: string;
        };
        JoinTokenResponse: {
            join_token: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            node_id: string;
            name: string;
            platform?: string;
            public_key: string;
            assigned_ip?: string;
            /** @enum {string} */
            status: "active" | "revoked";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_handshake_at?: string;
            online?: boolean;
            /** Format: int64 */
            rx_bytes?: number;
            /** Format: int64 */
            tx_bytes?: number;
        };
        CreateDeviceRequest: {
            name: string;
            /** Format: uuid */
            node_id: string;
            platform?: string;
            public_key?: string;
            /** Format: uuid */
            user_id?: string;
            full_tunnel?: boolean;
        };
        CreateDeviceResponse: {
            device: components["schemas"]["Device"];
            private_key?: string;
            config?: string;
        };
        InviteRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        Member: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            /** @enum {string} */
            status: "active" | "deactivated";
            email_verified: boolean;
            /** Format: date-time */
            joined_at: string;
        };
        ChangeRoleRequest: {
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        AcceptInviteRequest: {
            token: string;
            name?: string;
            password?: string;
        };
        DomainClaimRequest: {
            domain: string;
        };
        DomainClaimResponse: {
            /** @description Publish this exact value as a TXT record on the domain, then verify. */
            txt_record: string;
        };
        DomainVerifyRequest: {
            domain: string;
        };
        SsoConfigRequest: {
            client_id: string;
            client_secret: string;
            /** @description Required for Microsoft (the org's Entra tenant ID); unused by Google. */
            tenant_id?: string;
            enabled: boolean;
        };
        SsoConfigView: {
            /** @enum {string} */
            provider: "google" | "microsoft";
            client_id: string;
            tenant_id?: string;
            enabled: boolean;
            secret_fingerprint: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            email_verified: boolean;
        };
        ActivityEntry: {
            action: string;
            target_type?: string;
            target_id?: string;
            /** Format: uuid */
            actor_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        AuditLogEntry: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            actor_id?: string;
            action: string;
            target_type?: string;
            target_id?: string;
            details: {
                [key: string]: unknown;
            };
        };
        OrgOverview: {
            members: number;
            devices: number;
            nodes: number;
            online: number;
            recent_activity: components["schemas"]["ActivityEntry"][];
        };
        Meta: {
            /** @enum {string} */
            edition: "open" | "enterprise";
            sso_providers: ("google" | "microsoft")[];
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenRequest: {
            token: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            password: string;
        };
        /** @description Standard error envelope for every non-2xx response. Chosen over bare
         *     RFC 7807 so the correlation `request_id` is a first-class field the SPA
         *     and CLI can surface directly; `code` is stable for programmatic handling.
         *      */
        Error: {
            error: {
                /**
                 * @description Stable, machine-readable error code.
                 * @example not_found
                 */
                code: string;
                /** @description Human-readable explanation. */
                message: string;
                /** @description Correlation ID; match against server logs. */
                request_id?: string;
                /** @description Field-level problems (e.g. validation failures). */
                details?: components["schemas"]["ErrorDetail"][];
            };
        };
        ErrorDetail: {
            /** @description Dotted path to the offending field, when applicable. */
            field?: string;
            /** @description What is wrong with this field. */
            message: string;
        };
    };
    responses: {
        /** @description Error response. */
        Error: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Correlation ID for this request; also appears in server logs. */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is alive. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Accepted. Returns the same generic result whether or not the email was already registered. */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials valid. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Verified. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Accepted. Generic result regardless of whether the email exists. */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password updated. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment metadata. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description If verification is pending, an email has been sent. */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    startSsoLogin: {
        parameters: {
            query: {
                /** @description Organization slug whose SSO config to use. */
                org: string;
            };
            header?: never;
            path: {
                provider: "google" | "microsoft";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The IdP redirect URL for the client to navigate to. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoRedirect"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    ssoCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: "google" | "microsoft";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated — session cookie set, browser redirected to the app. */
            302: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getSsoConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                provider: "google" | "microsoft";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The provider config (no secret material — only a keyed fingerprint). */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoConfigView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setSsoConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                provider: "google" | "microsoft";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoConfigRequest"];
            };
        };
        responses: {
            /** @description Saved. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    cliAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliAuthorizeRequest"];
            };
        };
        responses: {
            /** @description One-time code minted; the SPA redirects the browser to the loopback. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliAuthorizeResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cliToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliTokenRequest"];
            };
        };
        responses: {
            /** @description The dedicated CLI credential — shown exactly once, never re-served. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliTokenResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCliCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's credentials (fingerprints, never token material). */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliCredential"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeCliCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked (idempotent for an already-revoked credential). */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    cliDeviceStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device flow started. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliDeviceStartResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cliDeviceApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliDeviceApproveRequest"];
            };
        };
        responses: {
            /** @description Approved — the polling CLI will receive its credential. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cliDeviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CliDeviceTokenRequest"];
            };
        };
        responses: {
            /** @description The dedicated CLI credential — shown exactly once. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CliTokenResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    enrollAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Enrolled — returns the signed agent certificate and the CA. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    issueJoinToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinTokenRequest"];
            };
        };
        responses: {
            /** @description The join token (shown once). */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinTokenResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getOrgOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org overview. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOverview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                /** @description Filter by acting user (must be an org member). */
                actor?: string;
                action?: string;
                /** @description created_at >= this. */
                from?: string;
                /** @description created_at <= this. */
                to?: string;
                cursor_ts?: string;
                cursor_id?: string;
                limit?: number;
            };
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit entries, newest first. Fewer than `limit` means the last page. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntry"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description The created device (with a one-time private key if server-generated). */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDeviceResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupRequest"];
            };
        };
        responses: {
            /** @description Created group. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupRequest"];
            };
        };
        responses: {
            /** @description Updated group. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGroupMemberRequest"];
            };
        };
        responses: {
            /** @description Added (idempotent). */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resources. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceRequest"];
            };
        };
        responses: {
            /** @description Created resource. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceRequest"];
            };
        };
        responses: {
            /** @description Updated resource. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPolicyRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPolicyRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePolicyRuleRequest"];
            };
        };
        responses: {
            /** @description Created rule. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deletePolicyRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getZeroTrustMode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current mode. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZeroTrustMode"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setZeroTrustMode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZeroTrustMode"];
            };
        };
        responses: {
            /** @description Updated mode. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZeroTrustMode"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Accepted; the account is a member. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Invitation created (accept token returned for the dashboard link). */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreated"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Invitation re-sent. */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The members. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    changeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Role changed. (Client refetches the roster.) */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deactivateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    reactivateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reactivated. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createDomainClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainClaimRequest"];
            };
        };
        responses: {
            /** @description Claim created — publish the returned TXT record, then verify. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainClaimResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    verifyDomainClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainVerifyRequest"];
            };
        };
        responses: {
            /** @description Verified. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericMessage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description The created organization. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description The updated organization. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resizePool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolCidrRequest"];
            };
        };
        responses: {
            /** @description The updated organization (also returned unchanged for an idempotent no-op resize). */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description The shrink would strand live allocations; none were changed. */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResizeConflict"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
